/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/synthetics/v1alpha1"
	scheme "kubeform.dev/provider-datadog-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GlobalVariablesGetter has a method to return a GlobalVariableInterface.
// A group's client should implement this interface.
type GlobalVariablesGetter interface {
	GlobalVariables(namespace string) GlobalVariableInterface
}

// GlobalVariableInterface has methods to work with GlobalVariable resources.
type GlobalVariableInterface interface {
	Create(ctx context.Context, globalVariable *v1alpha1.GlobalVariable, opts v1.CreateOptions) (*v1alpha1.GlobalVariable, error)
	Update(ctx context.Context, globalVariable *v1alpha1.GlobalVariable, opts v1.UpdateOptions) (*v1alpha1.GlobalVariable, error)
	UpdateStatus(ctx context.Context, globalVariable *v1alpha1.GlobalVariable, opts v1.UpdateOptions) (*v1alpha1.GlobalVariable, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.GlobalVariable, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.GlobalVariableList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalVariable, err error)
	GlobalVariableExpansion
}

// globalVariables implements GlobalVariableInterface
type globalVariables struct {
	client rest.Interface
	ns     string
}

// newGlobalVariables returns a GlobalVariables
func newGlobalVariables(c *SyntheticsV1alpha1Client, namespace string) *globalVariables {
	return &globalVariables{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the globalVariable, and returns the corresponding globalVariable object, and an error if there is any.
func (c *globalVariables) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GlobalVariable, err error) {
	result = &v1alpha1.GlobalVariable{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalvariables").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GlobalVariables that match those selectors.
func (c *globalVariables) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GlobalVariableList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GlobalVariableList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("globalvariables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested globalVariables.
func (c *globalVariables) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("globalvariables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a globalVariable and creates it.  Returns the server's representation of the globalVariable, and an error, if there is any.
func (c *globalVariables) Create(ctx context.Context, globalVariable *v1alpha1.GlobalVariable, opts v1.CreateOptions) (result *v1alpha1.GlobalVariable, err error) {
	result = &v1alpha1.GlobalVariable{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("globalvariables").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalVariable).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a globalVariable and updates it. Returns the server's representation of the globalVariable, and an error, if there is any.
func (c *globalVariables) Update(ctx context.Context, globalVariable *v1alpha1.GlobalVariable, opts v1.UpdateOptions) (result *v1alpha1.GlobalVariable, err error) {
	result = &v1alpha1.GlobalVariable{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalvariables").
		Name(globalVariable.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalVariable).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *globalVariables) UpdateStatus(ctx context.Context, globalVariable *v1alpha1.GlobalVariable, opts v1.UpdateOptions) (result *v1alpha1.GlobalVariable, err error) {
	result = &v1alpha1.GlobalVariable{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("globalvariables").
		Name(globalVariable.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(globalVariable).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the globalVariable and deletes it. Returns an error if one occurs.
func (c *globalVariables) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalvariables").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *globalVariables) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("globalvariables").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched globalVariable.
func (c *globalVariables) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GlobalVariable, err error) {
	result = &v1alpha1.GlobalVariable{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("globalvariables").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
