/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/synthetics/v1alpha1"
	scheme "kubeform.dev/provider-datadog-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// PrivateLocationsGetter has a method to return a PrivateLocationInterface.
// A group's client should implement this interface.
type PrivateLocationsGetter interface {
	PrivateLocations(namespace string) PrivateLocationInterface
}

// PrivateLocationInterface has methods to work with PrivateLocation resources.
type PrivateLocationInterface interface {
	Create(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.CreateOptions) (*v1alpha1.PrivateLocation, error)
	Update(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.UpdateOptions) (*v1alpha1.PrivateLocation, error)
	UpdateStatus(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.UpdateOptions) (*v1alpha1.PrivateLocation, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.PrivateLocation, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.PrivateLocationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrivateLocation, err error)
	PrivateLocationExpansion
}

// privateLocations implements PrivateLocationInterface
type privateLocations struct {
	client rest.Interface
	ns     string
}

// newPrivateLocations returns a PrivateLocations
func newPrivateLocations(c *SyntheticsV1alpha1Client, namespace string) *privateLocations {
	return &privateLocations{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the privateLocation, and returns the corresponding privateLocation object, and an error if there is any.
func (c *privateLocations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PrivateLocation, err error) {
	result = &v1alpha1.PrivateLocation{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("privatelocations").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of PrivateLocations that match those selectors.
func (c *privateLocations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrivateLocationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.PrivateLocationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("privatelocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested privateLocations.
func (c *privateLocations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("privatelocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a privateLocation and creates it.  Returns the server's representation of the privateLocation, and an error, if there is any.
func (c *privateLocations) Create(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.CreateOptions) (result *v1alpha1.PrivateLocation, err error) {
	result = &v1alpha1.PrivateLocation{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("privatelocations").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(privateLocation).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a privateLocation and updates it. Returns the server's representation of the privateLocation, and an error, if there is any.
func (c *privateLocations) Update(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.UpdateOptions) (result *v1alpha1.PrivateLocation, err error) {
	result = &v1alpha1.PrivateLocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("privatelocations").
		Name(privateLocation.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(privateLocation).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *privateLocations) UpdateStatus(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.UpdateOptions) (result *v1alpha1.PrivateLocation, err error) {
	result = &v1alpha1.PrivateLocation{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("privatelocations").
		Name(privateLocation.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(privateLocation).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the privateLocation and deletes it. Returns an error if one occurs.
func (c *privateLocations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("privatelocations").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *privateLocations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("privatelocations").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched privateLocation.
func (c *privateLocations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrivateLocation, err error) {
	result = &v1alpha1.PrivateLocation{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("privatelocations").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
