/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/dashboard/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeLists implements ListInterface
type FakeLists struct {
	Fake *FakeDashboardV1alpha1
	ns   string
}

var listsResource = schema.GroupVersionResource{Group: "dashboard.datadog.kubeform.com", Version: "v1alpha1", Resource: "lists"}

var listsKind = schema.GroupVersionKind{Group: "dashboard.datadog.kubeform.com", Version: "v1alpha1", Kind: "List"}

// Get takes name of the list, and returns the corresponding list object, and an error if there is any.
func (c *FakeLists) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(listsResource, c.ns, name), &v1alpha1.List{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.List), err
}

// List takes label and field selectors, and returns the list of Lists that match those selectors.
func (c *FakeLists) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ListList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(listsResource, listsKind, c.ns, opts), &v1alpha1.ListList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ListList{ListMeta: obj.(*v1alpha1.ListList).ListMeta}
	for _, item := range obj.(*v1alpha1.ListList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested lists.
func (c *FakeLists) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(listsResource, c.ns, opts))

}

// Create takes the representation of a list and creates it.  Returns the server's representation of the list, and an error, if there is any.
func (c *FakeLists) Create(ctx context.Context, list *v1alpha1.List, opts v1.CreateOptions) (result *v1alpha1.List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(listsResource, c.ns, list), &v1alpha1.List{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.List), err
}

// Update takes the representation of a list and updates it. Returns the server's representation of the list, and an error, if there is any.
func (c *FakeLists) Update(ctx context.Context, list *v1alpha1.List, opts v1.UpdateOptions) (result *v1alpha1.List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(listsResource, c.ns, list), &v1alpha1.List{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.List), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeLists) UpdateStatus(ctx context.Context, list *v1alpha1.List, opts v1.UpdateOptions) (*v1alpha1.List, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(listsResource, "status", c.ns, list), &v1alpha1.List{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.List), err
}

// Delete takes name of the list and deletes it. Returns an error if one occurs.
func (c *FakeLists) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(listsResource, c.ns, name), &v1alpha1.List{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeLists) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(listsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ListList{})
	return err
}

// Patch applies the patch and returns the patched list.
func (c *FakeLists) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.List, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(listsResource, c.ns, name, pt, data, subresources...), &v1alpha1.List{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.List), err
}
