/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AwsListerExpansion allows custom methods to be added to
// AwsLister.
type AwsListerExpansion interface{}

// AwsNamespaceListerExpansion allows custom methods to be added to
// AwsNamespaceLister.
type AwsNamespaceListerExpansion interface{}

// AwsLambdaArnListerExpansion allows custom methods to be added to
// AwsLambdaArnLister.
type AwsLambdaArnListerExpansion interface{}

// AwsLambdaArnNamespaceListerExpansion allows custom methods to be added to
// AwsLambdaArnNamespaceLister.
type AwsLambdaArnNamespaceListerExpansion interface{}

// AwsLogCollectionListerExpansion allows custom methods to be added to
// AwsLogCollectionLister.
type AwsLogCollectionListerExpansion interface{}

// AwsLogCollectionNamespaceListerExpansion allows custom methods to be added to
// AwsLogCollectionNamespaceLister.
type AwsLogCollectionNamespaceListerExpansion interface{}

// AwsTagFilterListerExpansion allows custom methods to be added to
// AwsTagFilterLister.
type AwsTagFilterListerExpansion interface{}

// AwsTagFilterNamespaceListerExpansion allows custom methods to be added to
// AwsTagFilterNamespaceLister.
type AwsTagFilterNamespaceListerExpansion interface{}

// AzureListerExpansion allows custom methods to be added to
// AzureLister.
type AzureListerExpansion interface{}

// AzureNamespaceListerExpansion allows custom methods to be added to
// AzureNamespaceLister.
type AzureNamespaceListerExpansion interface{}

// GcpListerExpansion allows custom methods to be added to
// GcpLister.
type GcpListerExpansion interface{}

// GcpNamespaceListerExpansion allows custom methods to be added to
// GcpNamespaceLister.
type GcpNamespaceListerExpansion interface{}

// PagerdutyListerExpansion allows custom methods to be added to
// PagerdutyLister.
type PagerdutyListerExpansion interface{}

// PagerdutyNamespaceListerExpansion allows custom methods to be added to
// PagerdutyNamespaceLister.
type PagerdutyNamespaceListerExpansion interface{}

// PagerdutyServiceObjectListerExpansion allows custom methods to be added to
// PagerdutyServiceObjectLister.
type PagerdutyServiceObjectListerExpansion interface{}

// PagerdutyServiceObjectNamespaceListerExpansion allows custom methods to be added to
// PagerdutyServiceObjectNamespaceLister.
type PagerdutyServiceObjectNamespaceListerExpansion interface{}

// SlackChannelListerExpansion allows custom methods to be added to
// SlackChannelLister.
type SlackChannelListerExpansion interface{}

// SlackChannelNamespaceListerExpansion allows custom methods to be added to
// SlackChannelNamespaceLister.
type SlackChannelNamespaceListerExpansion interface{}
