/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/provider-datadog-api/apis/integration/v1alpha1"

	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// PagerdutyServiceObjectLister helps list PagerdutyServiceObjects.
// All objects returned here must be treated as read-only.
type PagerdutyServiceObjectLister interface {
	// List lists all PagerdutyServiceObjects in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PagerdutyServiceObject, err error)
	// PagerdutyServiceObjects returns an object that can list and get PagerdutyServiceObjects.
	PagerdutyServiceObjects(namespace string) PagerdutyServiceObjectNamespaceLister
	PagerdutyServiceObjectListerExpansion
}

// pagerdutyServiceObjectLister implements the PagerdutyServiceObjectLister interface.
type pagerdutyServiceObjectLister struct {
	indexer cache.Indexer
}

// NewPagerdutyServiceObjectLister returns a new PagerdutyServiceObjectLister.
func NewPagerdutyServiceObjectLister(indexer cache.Indexer) PagerdutyServiceObjectLister {
	return &pagerdutyServiceObjectLister{indexer: indexer}
}

// List lists all PagerdutyServiceObjects in the indexer.
func (s *pagerdutyServiceObjectLister) List(selector labels.Selector) (ret []*v1alpha1.PagerdutyServiceObject, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PagerdutyServiceObject))
	})
	return ret, err
}

// PagerdutyServiceObjects returns an object that can list and get PagerdutyServiceObjects.
func (s *pagerdutyServiceObjectLister) PagerdutyServiceObjects(namespace string) PagerdutyServiceObjectNamespaceLister {
	return pagerdutyServiceObjectNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// PagerdutyServiceObjectNamespaceLister helps list and get PagerdutyServiceObjects.
// All objects returned here must be treated as read-only.
type PagerdutyServiceObjectNamespaceLister interface {
	// List lists all PagerdutyServiceObjects in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.PagerdutyServiceObject, err error)
	// Get retrieves the PagerdutyServiceObject from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.PagerdutyServiceObject, error)
	PagerdutyServiceObjectNamespaceListerExpansion
}

// pagerdutyServiceObjectNamespaceLister implements the PagerdutyServiceObjectNamespaceLister
// interface.
type pagerdutyServiceObjectNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all PagerdutyServiceObjects in the indexer for a given namespace.
func (s pagerdutyServiceObjectNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.PagerdutyServiceObject, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.PagerdutyServiceObject))
	})
	return ret, err
}

// Get retrieves the PagerdutyServiceObject from the indexer for a given namespace and name.
func (s pagerdutyServiceObjectNamespaceLister) Get(name string) (*v1alpha1.PagerdutyServiceObject, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("pagerdutyserviceobject"), name)
	}
	return obj.(*v1alpha1.PagerdutyServiceObject), nil
}
