/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/metric/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMetadatas implements MetadataInterface
type FakeMetadatas struct {
	Fake *FakeMetricV1alpha1
	ns   string
}

var metadatasResource = schema.GroupVersionResource{Group: "metric.datadog.kubeform.com", Version: "v1alpha1", Resource: "metadatas"}

var metadatasKind = schema.GroupVersionKind{Group: "metric.datadog.kubeform.com", Version: "v1alpha1", Kind: "Metadata"}

// Get takes name of the metadata, and returns the corresponding metadata object, and an error if there is any.
func (c *FakeMetadatas) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Metadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(metadatasResource, c.ns, name), &v1alpha1.Metadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Metadata), err
}

// List takes label and field selectors, and returns the list of Metadatas that match those selectors.
func (c *FakeMetadatas) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MetadataList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(metadatasResource, metadatasKind, c.ns, opts), &v1alpha1.MetadataList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MetadataList{ListMeta: obj.(*v1alpha1.MetadataList).ListMeta}
	for _, item := range obj.(*v1alpha1.MetadataList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested metadatas.
func (c *FakeMetadatas) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(metadatasResource, c.ns, opts))

}

// Create takes the representation of a metadata and creates it.  Returns the server's representation of the metadata, and an error, if there is any.
func (c *FakeMetadatas) Create(ctx context.Context, metadata *v1alpha1.Metadata, opts v1.CreateOptions) (result *v1alpha1.Metadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(metadatasResource, c.ns, metadata), &v1alpha1.Metadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Metadata), err
}

// Update takes the representation of a metadata and updates it. Returns the server's representation of the metadata, and an error, if there is any.
func (c *FakeMetadatas) Update(ctx context.Context, metadata *v1alpha1.Metadata, opts v1.UpdateOptions) (result *v1alpha1.Metadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(metadatasResource, c.ns, metadata), &v1alpha1.Metadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Metadata), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMetadatas) UpdateStatus(ctx context.Context, metadata *v1alpha1.Metadata, opts v1.UpdateOptions) (*v1alpha1.Metadata, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(metadatasResource, "status", c.ns, metadata), &v1alpha1.Metadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Metadata), err
}

// Delete takes name of the metadata and deletes it. Returns an error if one occurs.
func (c *FakeMetadatas) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(metadatasResource, c.ns, name), &v1alpha1.Metadata{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMetadatas) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(metadatasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MetadataList{})
	return err
}

// Patch applies the patch and returns the patched metadata.
func (c *FakeMetadatas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Metadata, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(metadatasResource, c.ns, name, pt, data, subresources...), &v1alpha1.Metadata{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Metadata), err
}
