/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/integration/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsLambdaArns implements AwsLambdaArnInterface
type FakeAwsLambdaArns struct {
	Fake *FakeIntegrationV1alpha1
	ns   string
}

var awslambdaarnsResource = schema.GroupVersionResource{Group: "integration.datadog.kubeform.com", Version: "v1alpha1", Resource: "awslambdaarns"}

var awslambdaarnsKind = schema.GroupVersionKind{Group: "integration.datadog.kubeform.com", Version: "v1alpha1", Kind: "AwsLambdaArn"}

// Get takes name of the awsLambdaArn, and returns the corresponding awsLambdaArn object, and an error if there is any.
func (c *FakeAwsLambdaArns) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AwsLambdaArn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awslambdaarnsResource, c.ns, name), &v1alpha1.AwsLambdaArn{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsLambdaArn), err
}

// List takes label and field selectors, and returns the list of AwsLambdaArns that match those selectors.
func (c *FakeAwsLambdaArns) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AwsLambdaArnList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awslambdaarnsResource, awslambdaarnsKind, c.ns, opts), &v1alpha1.AwsLambdaArnList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsLambdaArnList{ListMeta: obj.(*v1alpha1.AwsLambdaArnList).ListMeta}
	for _, item := range obj.(*v1alpha1.AwsLambdaArnList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsLambdaArns.
func (c *FakeAwsLambdaArns) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awslambdaarnsResource, c.ns, opts))

}

// Create takes the representation of a awsLambdaArn and creates it.  Returns the server's representation of the awsLambdaArn, and an error, if there is any.
func (c *FakeAwsLambdaArns) Create(ctx context.Context, awsLambdaArn *v1alpha1.AwsLambdaArn, opts v1.CreateOptions) (result *v1alpha1.AwsLambdaArn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awslambdaarnsResource, c.ns, awsLambdaArn), &v1alpha1.AwsLambdaArn{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsLambdaArn), err
}

// Update takes the representation of a awsLambdaArn and updates it. Returns the server's representation of the awsLambdaArn, and an error, if there is any.
func (c *FakeAwsLambdaArns) Update(ctx context.Context, awsLambdaArn *v1alpha1.AwsLambdaArn, opts v1.UpdateOptions) (result *v1alpha1.AwsLambdaArn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awslambdaarnsResource, c.ns, awsLambdaArn), &v1alpha1.AwsLambdaArn{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsLambdaArn), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAwsLambdaArns) UpdateStatus(ctx context.Context, awsLambdaArn *v1alpha1.AwsLambdaArn, opts v1.UpdateOptions) (*v1alpha1.AwsLambdaArn, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(awslambdaarnsResource, "status", c.ns, awsLambdaArn), &v1alpha1.AwsLambdaArn{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsLambdaArn), err
}

// Delete takes name of the awsLambdaArn and deletes it. Returns an error if one occurs.
func (c *FakeAwsLambdaArns) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awslambdaarnsResource, c.ns, name), &v1alpha1.AwsLambdaArn{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsLambdaArns) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awslambdaarnsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsLambdaArnList{})
	return err
}

// Patch applies the patch and returns the patched awsLambdaArn.
func (c *FakeAwsLambdaArns) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AwsLambdaArn, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awslambdaarnsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AwsLambdaArn{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsLambdaArn), err
}
