/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/integration/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePagerduties implements PagerdutyInterface
type FakePagerduties struct {
	Fake *FakeIntegrationV1alpha1
	ns   string
}

var pagerdutiesResource = schema.GroupVersionResource{Group: "integration.datadog.kubeform.com", Version: "v1alpha1", Resource: "pagerduties"}

var pagerdutiesKind = schema.GroupVersionKind{Group: "integration.datadog.kubeform.com", Version: "v1alpha1", Kind: "Pagerduty"}

// Get takes name of the pagerduty, and returns the corresponding pagerduty object, and an error if there is any.
func (c *FakePagerduties) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Pagerduty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(pagerdutiesResource, c.ns, name), &v1alpha1.Pagerduty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pagerduty), err
}

// List takes label and field selectors, and returns the list of Pagerduties that match those selectors.
func (c *FakePagerduties) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PagerdutyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(pagerdutiesResource, pagerdutiesKind, c.ns, opts), &v1alpha1.PagerdutyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PagerdutyList{ListMeta: obj.(*v1alpha1.PagerdutyList).ListMeta}
	for _, item := range obj.(*v1alpha1.PagerdutyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested pagerduties.
func (c *FakePagerduties) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(pagerdutiesResource, c.ns, opts))

}

// Create takes the representation of a pagerduty and creates it.  Returns the server's representation of the pagerduty, and an error, if there is any.
func (c *FakePagerduties) Create(ctx context.Context, pagerduty *v1alpha1.Pagerduty, opts v1.CreateOptions) (result *v1alpha1.Pagerduty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(pagerdutiesResource, c.ns, pagerduty), &v1alpha1.Pagerduty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pagerduty), err
}

// Update takes the representation of a pagerduty and updates it. Returns the server's representation of the pagerduty, and an error, if there is any.
func (c *FakePagerduties) Update(ctx context.Context, pagerduty *v1alpha1.Pagerduty, opts v1.UpdateOptions) (result *v1alpha1.Pagerduty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(pagerdutiesResource, c.ns, pagerduty), &v1alpha1.Pagerduty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pagerduty), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePagerduties) UpdateStatus(ctx context.Context, pagerduty *v1alpha1.Pagerduty, opts v1.UpdateOptions) (*v1alpha1.Pagerduty, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(pagerdutiesResource, "status", c.ns, pagerduty), &v1alpha1.Pagerduty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pagerduty), err
}

// Delete takes name of the pagerduty and deletes it. Returns an error if one occurs.
func (c *FakePagerduties) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(pagerdutiesResource, c.ns, name), &v1alpha1.Pagerduty{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePagerduties) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(pagerdutiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PagerdutyList{})
	return err
}

// Patch applies the patch and returns the patched pagerduty.
func (c *FakePagerduties) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Pagerduty, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(pagerdutiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Pagerduty{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Pagerduty), err
}
