/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/integration/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAwsTagFilters implements AwsTagFilterInterface
type FakeAwsTagFilters struct {
	Fake *FakeIntegrationV1alpha1
	ns   string
}

var awstagfiltersResource = schema.GroupVersionResource{Group: "integration.datadog.kubeform.com", Version: "v1alpha1", Resource: "awstagfilters"}

var awstagfiltersKind = schema.GroupVersionKind{Group: "integration.datadog.kubeform.com", Version: "v1alpha1", Kind: "AwsTagFilter"}

// Get takes name of the awsTagFilter, and returns the corresponding awsTagFilter object, and an error if there is any.
func (c *FakeAwsTagFilters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AwsTagFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(awstagfiltersResource, c.ns, name), &v1alpha1.AwsTagFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsTagFilter), err
}

// List takes label and field selectors, and returns the list of AwsTagFilters that match those selectors.
func (c *FakeAwsTagFilters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AwsTagFilterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(awstagfiltersResource, awstagfiltersKind, c.ns, opts), &v1alpha1.AwsTagFilterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AwsTagFilterList{ListMeta: obj.(*v1alpha1.AwsTagFilterList).ListMeta}
	for _, item := range obj.(*v1alpha1.AwsTagFilterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested awsTagFilters.
func (c *FakeAwsTagFilters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(awstagfiltersResource, c.ns, opts))

}

// Create takes the representation of a awsTagFilter and creates it.  Returns the server's representation of the awsTagFilter, and an error, if there is any.
func (c *FakeAwsTagFilters) Create(ctx context.Context, awsTagFilter *v1alpha1.AwsTagFilter, opts v1.CreateOptions) (result *v1alpha1.AwsTagFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(awstagfiltersResource, c.ns, awsTagFilter), &v1alpha1.AwsTagFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsTagFilter), err
}

// Update takes the representation of a awsTagFilter and updates it. Returns the server's representation of the awsTagFilter, and an error, if there is any.
func (c *FakeAwsTagFilters) Update(ctx context.Context, awsTagFilter *v1alpha1.AwsTagFilter, opts v1.UpdateOptions) (result *v1alpha1.AwsTagFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(awstagfiltersResource, c.ns, awsTagFilter), &v1alpha1.AwsTagFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsTagFilter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAwsTagFilters) UpdateStatus(ctx context.Context, awsTagFilter *v1alpha1.AwsTagFilter, opts v1.UpdateOptions) (*v1alpha1.AwsTagFilter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(awstagfiltersResource, "status", c.ns, awsTagFilter), &v1alpha1.AwsTagFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsTagFilter), err
}

// Delete takes name of the awsTagFilter and deletes it. Returns an error if one occurs.
func (c *FakeAwsTagFilters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(awstagfiltersResource, c.ns, name), &v1alpha1.AwsTagFilter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAwsTagFilters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(awstagfiltersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AwsTagFilterList{})
	return err
}

// Patch applies the patch and returns the patched awsTagFilter.
func (c *FakeAwsTagFilters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AwsTagFilter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(awstagfiltersResource, c.ns, name, pt, data, subresources...), &v1alpha1.AwsTagFilter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AwsTagFilter), err
}
