/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/downtime/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDowntimes implements DowntimeInterface
type FakeDowntimes struct {
	Fake *FakeDowntimeV1alpha1
	ns   string
}

var downtimesResource = schema.GroupVersionResource{Group: "downtime.datadog.kubeform.com", Version: "v1alpha1", Resource: "downtimes"}

var downtimesKind = schema.GroupVersionKind{Group: "downtime.datadog.kubeform.com", Version: "v1alpha1", Kind: "Downtime"}

// Get takes name of the downtime, and returns the corresponding downtime object, and an error if there is any.
func (c *FakeDowntimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Downtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(downtimesResource, c.ns, name), &v1alpha1.Downtime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Downtime), err
}

// List takes label and field selectors, and returns the list of Downtimes that match those selectors.
func (c *FakeDowntimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DowntimeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(downtimesResource, downtimesKind, c.ns, opts), &v1alpha1.DowntimeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DowntimeList{ListMeta: obj.(*v1alpha1.DowntimeList).ListMeta}
	for _, item := range obj.(*v1alpha1.DowntimeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested downtimes.
func (c *FakeDowntimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(downtimesResource, c.ns, opts))

}

// Create takes the representation of a downtime and creates it.  Returns the server's representation of the downtime, and an error, if there is any.
func (c *FakeDowntimes) Create(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.CreateOptions) (result *v1alpha1.Downtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(downtimesResource, c.ns, downtime), &v1alpha1.Downtime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Downtime), err
}

// Update takes the representation of a downtime and updates it. Returns the server's representation of the downtime, and an error, if there is any.
func (c *FakeDowntimes) Update(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.UpdateOptions) (result *v1alpha1.Downtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(downtimesResource, c.ns, downtime), &v1alpha1.Downtime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Downtime), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDowntimes) UpdateStatus(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.UpdateOptions) (*v1alpha1.Downtime, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(downtimesResource, "status", c.ns, downtime), &v1alpha1.Downtime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Downtime), err
}

// Delete takes name of the downtime and deletes it. Returns an error if one occurs.
func (c *FakeDowntimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(downtimesResource, c.ns, name), &v1alpha1.Downtime{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDowntimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(downtimesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DowntimeList{})
	return err
}

// Patch applies the patch and returns the patched downtime.
func (c *FakeDowntimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Downtime, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(downtimesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Downtime{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Downtime), err
}
