// +build !ignore_autogenerated

/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1 "kmodules.xyz/client-go/api/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariable) DeepCopyInto(out *GlobalVariable) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariable.
func (in *GlobalVariable) DeepCopy() *GlobalVariable {
	if in == nil {
		return nil
	}
	out := new(GlobalVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalVariable) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariableList) DeepCopyInto(out *GlobalVariableList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GlobalVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariableList.
func (in *GlobalVariableList) DeepCopy() *GlobalVariableList {
	if in == nil {
		return nil
	}
	out := new(GlobalVariableList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GlobalVariableList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariableSpec) DeepCopyInto(out *GlobalVariableSpec) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(GlobalVariableSpecResource)
		(*in).DeepCopyInto(*out)
	}
	in.Resource.DeepCopyInto(&out.Resource)
	out.ProviderRef = in.ProviderRef
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariableSpec.
func (in *GlobalVariableSpec) DeepCopy() *GlobalVariableSpec {
	if in == nil {
		return nil
	}
	out := new(GlobalVariableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariableSpecParseTestOptions) DeepCopyInto(out *GlobalVariableSpecParseTestOptions) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Parser != nil {
		in, out := &in.Parser, &out.Parser
		*out = new(GlobalVariableSpecParseTestOptionsParser)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariableSpecParseTestOptions.
func (in *GlobalVariableSpecParseTestOptions) DeepCopy() *GlobalVariableSpecParseTestOptions {
	if in == nil {
		return nil
	}
	out := new(GlobalVariableSpecParseTestOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariableSpecParseTestOptionsParser) DeepCopyInto(out *GlobalVariableSpecParseTestOptionsParser) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariableSpecParseTestOptionsParser.
func (in *GlobalVariableSpecParseTestOptionsParser) DeepCopy() *GlobalVariableSpecParseTestOptionsParser {
	if in == nil {
		return nil
	}
	out := new(GlobalVariableSpecParseTestOptionsParser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariableSpecResource) DeepCopyInto(out *GlobalVariableSpecResource) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParseTestID != nil {
		in, out := &in.ParseTestID, &out.ParseTestID
		*out = new(string)
		**out = **in
	}
	if in.ParseTestOptions != nil {
		in, out := &in.ParseTestOptions, &out.ParseTestOptions
		*out = new(GlobalVariableSpecParseTestOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Secure != nil {
		in, out := &in.Secure, &out.Secure
		*out = new(bool)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariableSpecResource.
func (in *GlobalVariableSpecResource) DeepCopy() *GlobalVariableSpecResource {
	if in == nil {
		return nil
	}
	out := new(GlobalVariableSpecResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalVariableStatus) DeepCopyInto(out *GlobalVariableStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]apiv1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalVariableStatus.
func (in *GlobalVariableStatus) DeepCopy() *GlobalVariableStatus {
	if in == nil {
		return nil
	}
	out := new(GlobalVariableStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateLocation) DeepCopyInto(out *PrivateLocation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateLocation.
func (in *PrivateLocation) DeepCopy() *PrivateLocation {
	if in == nil {
		return nil
	}
	out := new(PrivateLocation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateLocation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateLocationList) DeepCopyInto(out *PrivateLocationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivateLocation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateLocationList.
func (in *PrivateLocationList) DeepCopy() *PrivateLocationList {
	if in == nil {
		return nil
	}
	out := new(PrivateLocationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivateLocationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateLocationSpec) DeepCopyInto(out *PrivateLocationSpec) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(PrivateLocationSpecResource)
		(*in).DeepCopyInto(*out)
	}
	in.Resource.DeepCopyInto(&out.Resource)
	out.ProviderRef = in.ProviderRef
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateLocationSpec.
func (in *PrivateLocationSpec) DeepCopy() *PrivateLocationSpec {
	if in == nil {
		return nil
	}
	out := new(PrivateLocationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateLocationSpecResource) DeepCopyInto(out *PrivateLocationSpecResource) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateLocationSpecResource.
func (in *PrivateLocationSpecResource) DeepCopy() *PrivateLocationSpecResource {
	if in == nil {
		return nil
	}
	out := new(PrivateLocationSpecResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivateLocationStatus) DeepCopyInto(out *PrivateLocationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]apiv1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivateLocationStatus.
func (in *PrivateLocationStatus) DeepCopy() *PrivateLocationStatus {
	if in == nil {
		return nil
	}
	out := new(PrivateLocationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Test) DeepCopyInto(out *Test) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Test.
func (in *Test) DeepCopy() *Test {
	if in == nil {
		return nil
	}
	out := new(Test)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Test) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestList) DeepCopyInto(out *TestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Test, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestList.
func (in *TestList) DeepCopy() *TestList {
	if in == nil {
		return nil
	}
	out := new(TestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpec) DeepCopyInto(out *TestSpec) {
	*out = *in
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(TestSpecResource)
		(*in).DeepCopyInto(*out)
	}
	in.Resource.DeepCopyInto(&out.Resource)
	out.ProviderRef = in.ProviderRef
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpec.
func (in *TestSpec) DeepCopy() *TestSpec {
	if in == nil {
		return nil
	}
	out := new(TestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStep) DeepCopyInto(out *TestSpecApiStep) {
	*out = *in
	if in.AllowFailure != nil {
		in, out := &in.AllowFailure, &out.AllowFailure
		*out = new(bool)
		**out = **in
	}
	if in.Assertion != nil {
		in, out := &in.Assertion, &out.Assertion
		*out = make([]TestSpecApiStepAssertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ExtractedValue != nil {
		in, out := &in.ExtractedValue, &out.ExtractedValue
		*out = make([]TestSpecApiStepExtractedValue, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.IsCritical != nil {
		in, out := &in.IsCritical, &out.IsCritical
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RequestBasicauth != nil {
		in, out := &in.RequestBasicauth, &out.RequestBasicauth
		*out = new(TestSpecApiStepRequestBasicauth)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestClientCertificate != nil {
		in, out := &in.RequestClientCertificate, &out.RequestClientCertificate
		*out = new(TestSpecApiStepRequestClientCertificate)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestDefinition != nil {
		in, out := &in.RequestDefinition, &out.RequestDefinition
		*out = new(TestSpecApiStepRequestDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestQuery != nil {
		in, out := &in.RequestQuery, &out.RequestQuery
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Subtype != nil {
		in, out := &in.Subtype, &out.Subtype
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStep.
func (in *TestSpecApiStep) DeepCopy() *TestSpecApiStep {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepAssertion) DeepCopyInto(out *TestSpecApiStepAssertion) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
	if in.Targetjsonpath != nil {
		in, out := &in.Targetjsonpath, &out.Targetjsonpath
		*out = new(TestSpecApiStepAssertionTargetjsonpath)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepAssertion.
func (in *TestSpecApiStepAssertion) DeepCopy() *TestSpecApiStepAssertion {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepAssertionTargetjsonpath) DeepCopyInto(out *TestSpecApiStepAssertionTargetjsonpath) {
	*out = *in
	if in.Jsonpath != nil {
		in, out := &in.Jsonpath, &out.Jsonpath
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Targetvalue != nil {
		in, out := &in.Targetvalue, &out.Targetvalue
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepAssertionTargetjsonpath.
func (in *TestSpecApiStepAssertionTargetjsonpath) DeepCopy() *TestSpecApiStepAssertionTargetjsonpath {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepAssertionTargetjsonpath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepExtractedValue) DeepCopyInto(out *TestSpecApiStepExtractedValue) {
	*out = *in
	if in.Field != nil {
		in, out := &in.Field, &out.Field
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parser != nil {
		in, out := &in.Parser, &out.Parser
		*out = new(TestSpecApiStepExtractedValueParser)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepExtractedValue.
func (in *TestSpecApiStepExtractedValue) DeepCopy() *TestSpecApiStepExtractedValue {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepExtractedValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepExtractedValueParser) DeepCopyInto(out *TestSpecApiStepExtractedValueParser) {
	*out = *in
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepExtractedValueParser.
func (in *TestSpecApiStepExtractedValueParser) DeepCopy() *TestSpecApiStepExtractedValueParser {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepExtractedValueParser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepRequestBasicauth) DeepCopyInto(out *TestSpecApiStepRequestBasicauth) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepRequestBasicauth.
func (in *TestSpecApiStepRequestBasicauth) DeepCopy() *TestSpecApiStepRequestBasicauth {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepRequestBasicauth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepRequestClientCertificate) DeepCopyInto(out *TestSpecApiStepRequestClientCertificate) {
	*out = *in
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(TestSpecApiStepRequestClientCertificateCert)
		(*in).DeepCopyInto(*out)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(TestSpecApiStepRequestClientCertificateKey)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepRequestClientCertificate.
func (in *TestSpecApiStepRequestClientCertificate) DeepCopy() *TestSpecApiStepRequestClientCertificate {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepRequestClientCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepRequestClientCertificateCert) DeepCopyInto(out *TestSpecApiStepRequestClientCertificateCert) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepRequestClientCertificateCert.
func (in *TestSpecApiStepRequestClientCertificateCert) DeepCopy() *TestSpecApiStepRequestClientCertificateCert {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepRequestClientCertificateCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepRequestClientCertificateKey) DeepCopyInto(out *TestSpecApiStepRequestClientCertificateKey) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepRequestClientCertificateKey.
func (in *TestSpecApiStepRequestClientCertificateKey) DeepCopy() *TestSpecApiStepRequestClientCertificateKey {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepRequestClientCertificateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecApiStepRequestDefinition) DeepCopyInto(out *TestSpecApiStepRequestDefinition) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
	if in.DnsServer != nil {
		in, out := &in.DnsServer, &out.DnsServer
		*out = new(string)
		**out = **in
	}
	if in.DnsServerPort != nil {
		in, out := &in.DnsServerPort, &out.DnsServerPort
		*out = new(int64)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.NoSavingResponseBody != nil {
		in, out := &in.NoSavingResponseBody, &out.NoSavingResponseBody
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfPackets != nil {
		in, out := &in.NumberOfPackets, &out.NumberOfPackets
		*out = new(int64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
	if in.ShouldTrackHops != nil {
		in, out := &in.ShouldTrackHops, &out.ShouldTrackHops
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int64)
		**out = **in
	}
	if in.Url != nil {
		in, out := &in.Url, &out.Url
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecApiStepRequestDefinition.
func (in *TestSpecApiStepRequestDefinition) DeepCopy() *TestSpecApiStepRequestDefinition {
	if in == nil {
		return nil
	}
	out := new(TestSpecApiStepRequestDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecAssertion) DeepCopyInto(out *TestSpecAssertion) {
	*out = *in
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = new(string)
		**out = **in
	}
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(string)
		**out = **in
	}
	if in.Targetjsonpath != nil {
		in, out := &in.Targetjsonpath, &out.Targetjsonpath
		*out = new(TestSpecAssertionTargetjsonpath)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecAssertion.
func (in *TestSpecAssertion) DeepCopy() *TestSpecAssertion {
	if in == nil {
		return nil
	}
	out := new(TestSpecAssertion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecAssertionTargetjsonpath) DeepCopyInto(out *TestSpecAssertionTargetjsonpath) {
	*out = *in
	if in.Jsonpath != nil {
		in, out := &in.Jsonpath, &out.Jsonpath
		*out = new(string)
		**out = **in
	}
	if in.Operator != nil {
		in, out := &in.Operator, &out.Operator
		*out = new(string)
		**out = **in
	}
	if in.Targetvalue != nil {
		in, out := &in.Targetvalue, &out.Targetvalue
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecAssertionTargetjsonpath.
func (in *TestSpecAssertionTargetjsonpath) DeepCopy() *TestSpecAssertionTargetjsonpath {
	if in == nil {
		return nil
	}
	out := new(TestSpecAssertionTargetjsonpath)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecBrowserStep) DeepCopyInto(out *TestSpecBrowserStep) {
	*out = *in
	if in.AllowFailure != nil {
		in, out := &in.AllowFailure, &out.AllowFailure
		*out = new(bool)
		**out = **in
	}
	if in.ForceElementUpdate != nil {
		in, out := &in.ForceElementUpdate, &out.ForceElementUpdate
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(TestSpecBrowserStepParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecBrowserStep.
func (in *TestSpecBrowserStep) DeepCopy() *TestSpecBrowserStep {
	if in == nil {
		return nil
	}
	out := new(TestSpecBrowserStep)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecBrowserStepParams) DeepCopyInto(out *TestSpecBrowserStepParams) {
	*out = *in
	if in.Attribute != nil {
		in, out := &in.Attribute, &out.Attribute
		*out = new(string)
		**out = **in
	}
	if in.Check != nil {
		in, out := &in.Check, &out.Check
		*out = new(string)
		**out = **in
	}
	if in.ClickType != nil {
		in, out := &in.ClickType, &out.ClickType
		*out = new(string)
		**out = **in
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Delay != nil {
		in, out := &in.Delay, &out.Delay
		*out = new(int64)
		**out = **in
	}
	if in.Element != nil {
		in, out := &in.Element, &out.Element
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.File != nil {
		in, out := &in.File, &out.File
		*out = new(string)
		**out = **in
	}
	if in.Files != nil {
		in, out := &in.Files, &out.Files
		*out = new(string)
		**out = **in
	}
	if in.Modifiers != nil {
		in, out := &in.Modifiers, &out.Modifiers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PlayingTabID != nil {
		in, out := &in.PlayingTabID, &out.PlayingTabID
		*out = new(string)
		**out = **in
	}
	if in.Request != nil {
		in, out := &in.Request, &out.Request
		*out = new(string)
		**out = **in
	}
	if in.SubtestPublicID != nil {
		in, out := &in.SubtestPublicID, &out.SubtestPublicID
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(string)
		**out = **in
	}
	if in.Variable != nil {
		in, out := &in.Variable, &out.Variable
		*out = new(TestSpecBrowserStepParamsVariable)
		(*in).DeepCopyInto(*out)
	}
	if in.WithClick != nil {
		in, out := &in.WithClick, &out.WithClick
		*out = new(bool)
		**out = **in
	}
	if in.X != nil {
		in, out := &in.X, &out.X
		*out = new(int64)
		**out = **in
	}
	if in.Y != nil {
		in, out := &in.Y, &out.Y
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecBrowserStepParams.
func (in *TestSpecBrowserStepParams) DeepCopy() *TestSpecBrowserStepParams {
	if in == nil {
		return nil
	}
	out := new(TestSpecBrowserStepParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecBrowserStepParamsVariable) DeepCopyInto(out *TestSpecBrowserStepParamsVariable) {
	*out = *in
	if in.Example != nil {
		in, out := &in.Example, &out.Example
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecBrowserStepParamsVariable.
func (in *TestSpecBrowserStepParamsVariable) DeepCopy() *TestSpecBrowserStepParamsVariable {
	if in == nil {
		return nil
	}
	out := new(TestSpecBrowserStepParamsVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecBrowserVariable) DeepCopyInto(out *TestSpecBrowserVariable) {
	*out = *in
	if in.Example != nil {
		in, out := &in.Example, &out.Example
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecBrowserVariable.
func (in *TestSpecBrowserVariable) DeepCopy() *TestSpecBrowserVariable {
	if in == nil {
		return nil
	}
	out := new(TestSpecBrowserVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecConfigVariable) DeepCopyInto(out *TestSpecConfigVariable) {
	*out = *in
	if in.Example != nil {
		in, out := &in.Example, &out.Example
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecConfigVariable.
func (in *TestSpecConfigVariable) DeepCopy() *TestSpecConfigVariable {
	if in == nil {
		return nil
	}
	out := new(TestSpecConfigVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecOptionsList) DeepCopyInto(out *TestSpecOptionsList) {
	*out = *in
	if in.AcceptSelfSigned != nil {
		in, out := &in.AcceptSelfSigned, &out.AcceptSelfSigned
		*out = new(bool)
		**out = **in
	}
	if in.AllowInsecure != nil {
		in, out := &in.AllowInsecure, &out.AllowInsecure
		*out = new(bool)
		**out = **in
	}
	if in.FollowRedirects != nil {
		in, out := &in.FollowRedirects, &out.FollowRedirects
		*out = new(bool)
		**out = **in
	}
	if in.MinFailureDuration != nil {
		in, out := &in.MinFailureDuration, &out.MinFailureDuration
		*out = new(int64)
		**out = **in
	}
	if in.MinLocationFailed != nil {
		in, out := &in.MinLocationFailed, &out.MinLocationFailed
		*out = new(int64)
		**out = **in
	}
	if in.MonitorName != nil {
		in, out := &in.MonitorName, &out.MonitorName
		*out = new(string)
		**out = **in
	}
	if in.MonitorOptions != nil {
		in, out := &in.MonitorOptions, &out.MonitorOptions
		*out = new(TestSpecOptionsListMonitorOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.MonitorPriority != nil {
		in, out := &in.MonitorPriority, &out.MonitorPriority
		*out = new(int64)
		**out = **in
	}
	if in.NoScreenshot != nil {
		in, out := &in.NoScreenshot, &out.NoScreenshot
		*out = new(bool)
		**out = **in
	}
	if in.Retry != nil {
		in, out := &in.Retry, &out.Retry
		*out = new(TestSpecOptionsListRetry)
		(*in).DeepCopyInto(*out)
	}
	if in.TickEvery != nil {
		in, out := &in.TickEvery, &out.TickEvery
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecOptionsList.
func (in *TestSpecOptionsList) DeepCopy() *TestSpecOptionsList {
	if in == nil {
		return nil
	}
	out := new(TestSpecOptionsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecOptionsListMonitorOptions) DeepCopyInto(out *TestSpecOptionsListMonitorOptions) {
	*out = *in
	if in.RenotifyInterval != nil {
		in, out := &in.RenotifyInterval, &out.RenotifyInterval
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecOptionsListMonitorOptions.
func (in *TestSpecOptionsListMonitorOptions) DeepCopy() *TestSpecOptionsListMonitorOptions {
	if in == nil {
		return nil
	}
	out := new(TestSpecOptionsListMonitorOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecOptionsListRetry) DeepCopyInto(out *TestSpecOptionsListRetry) {
	*out = *in
	if in.Count != nil {
		in, out := &in.Count, &out.Count
		*out = new(int64)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(int64)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecOptionsListRetry.
func (in *TestSpecOptionsListRetry) DeepCopy() *TestSpecOptionsListRetry {
	if in == nil {
		return nil
	}
	out := new(TestSpecOptionsListRetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecRequestBasicauth) DeepCopyInto(out *TestSpecRequestBasicauth) {
	*out = *in
	if in.Password != nil {
		in, out := &in.Password, &out.Password
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecRequestBasicauth.
func (in *TestSpecRequestBasicauth) DeepCopy() *TestSpecRequestBasicauth {
	if in == nil {
		return nil
	}
	out := new(TestSpecRequestBasicauth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecRequestClientCertificate) DeepCopyInto(out *TestSpecRequestClientCertificate) {
	*out = *in
	if in.Cert != nil {
		in, out := &in.Cert, &out.Cert
		*out = new(TestSpecRequestClientCertificateCert)
		(*in).DeepCopyInto(*out)
	}
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(TestSpecRequestClientCertificateKey)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecRequestClientCertificate.
func (in *TestSpecRequestClientCertificate) DeepCopy() *TestSpecRequestClientCertificate {
	if in == nil {
		return nil
	}
	out := new(TestSpecRequestClientCertificate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecRequestClientCertificateCert) DeepCopyInto(out *TestSpecRequestClientCertificateCert) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecRequestClientCertificateCert.
func (in *TestSpecRequestClientCertificateCert) DeepCopy() *TestSpecRequestClientCertificateCert {
	if in == nil {
		return nil
	}
	out := new(TestSpecRequestClientCertificateCert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecRequestClientCertificateKey) DeepCopyInto(out *TestSpecRequestClientCertificateKey) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecRequestClientCertificateKey.
func (in *TestSpecRequestClientCertificateKey) DeepCopy() *TestSpecRequestClientCertificateKey {
	if in == nil {
		return nil
	}
	out := new(TestSpecRequestClientCertificateKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecRequestDefinition) DeepCopyInto(out *TestSpecRequestDefinition) {
	*out = *in
	if in.Body != nil {
		in, out := &in.Body, &out.Body
		*out = new(string)
		**out = **in
	}
	if in.DnsServer != nil {
		in, out := &in.DnsServer, &out.DnsServer
		*out = new(string)
		**out = **in
	}
	if in.DnsServerPort != nil {
		in, out := &in.DnsServerPort, &out.DnsServerPort
		*out = new(int64)
		**out = **in
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Method != nil {
		in, out := &in.Method, &out.Method
		*out = new(string)
		**out = **in
	}
	if in.NoSavingResponseBody != nil {
		in, out := &in.NoSavingResponseBody, &out.NoSavingResponseBody
		*out = new(bool)
		**out = **in
	}
	if in.NumberOfPackets != nil {
		in, out := &in.NumberOfPackets, &out.NumberOfPackets
		*out = new(int64)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int64)
		**out = **in
	}
	if in.ShouldTrackHops != nil {
		in, out := &in.ShouldTrackHops, &out.ShouldTrackHops
		*out = new(bool)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(int64)
		**out = **in
	}
	if in.Url != nil {
		in, out := &in.Url, &out.Url
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecRequestDefinition.
func (in *TestSpecRequestDefinition) DeepCopy() *TestSpecRequestDefinition {
	if in == nil {
		return nil
	}
	out := new(TestSpecRequestDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestSpecResource) DeepCopyInto(out *TestSpecResource) {
	*out = *in
	if in.ApiStep != nil {
		in, out := &in.ApiStep, &out.ApiStep
		*out = make([]TestSpecApiStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Assertion != nil {
		in, out := &in.Assertion, &out.Assertion
		*out = make([]TestSpecAssertion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BrowserStep != nil {
		in, out := &in.BrowserStep, &out.BrowserStep
		*out = make([]TestSpecBrowserStep, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BrowserVariable != nil {
		in, out := &in.BrowserVariable, &out.BrowserVariable
		*out = make([]TestSpecBrowserVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ConfigVariable != nil {
		in, out := &in.ConfigVariable, &out.ConfigVariable
		*out = make([]TestSpecConfigVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DeviceIDS != nil {
		in, out := &in.DeviceIDS, &out.DeviceIDS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Locations != nil {
		in, out := &in.Locations, &out.Locations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Message != nil {
		in, out := &in.Message, &out.Message
		*out = new(string)
		**out = **in
	}
	if in.MonitorID != nil {
		in, out := &in.MonitorID, &out.MonitorID
		*out = new(int64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OptionsList != nil {
		in, out := &in.OptionsList, &out.OptionsList
		*out = new(TestSpecOptionsList)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestBasicauth != nil {
		in, out := &in.RequestBasicauth, &out.RequestBasicauth
		*out = new(TestSpecRequestBasicauth)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestClientCertificate != nil {
		in, out := &in.RequestClientCertificate, &out.RequestClientCertificate
		*out = new(TestSpecRequestClientCertificate)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestDefinition != nil {
		in, out := &in.RequestDefinition, &out.RequestDefinition
		*out = new(TestSpecRequestDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.RequestHeaders != nil {
		in, out := &in.RequestHeaders, &out.RequestHeaders
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.RequestQuery != nil {
		in, out := &in.RequestQuery, &out.RequestQuery
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.SetCookie != nil {
		in, out := &in.SetCookie, &out.SetCookie
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Subtype != nil {
		in, out := &in.Subtype, &out.Subtype
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestSpecResource.
func (in *TestSpecResource) DeepCopy() *TestSpecResource {
	if in == nil {
		return nil
	}
	out := new(TestSpecResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestStatus) DeepCopyInto(out *TestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]apiv1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestStatus.
func (in *TestStatus) DeepCopy() *TestStatus {
	if in == nil {
		return nil
	}
	out := new(TestStatus)
	in.DeepCopyInto(out)
	return out
}
