/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/slo/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCorrections implements CorrectionInterface
type FakeCorrections struct {
	Fake *FakeSloV1alpha1
	ns   string
}

var correctionsResource = schema.GroupVersionResource{Group: "slo.datadog.kubeform.com", Version: "v1alpha1", Resource: "corrections"}

var correctionsKind = schema.GroupVersionKind{Group: "slo.datadog.kubeform.com", Version: "v1alpha1", Kind: "Correction"}

// Get takes name of the correction, and returns the corresponding correction object, and an error if there is any.
func (c *FakeCorrections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Correction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(correctionsResource, c.ns, name), &v1alpha1.Correction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Correction), err
}

// List takes label and field selectors, and returns the list of Corrections that match those selectors.
func (c *FakeCorrections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CorrectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(correctionsResource, correctionsKind, c.ns, opts), &v1alpha1.CorrectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CorrectionList{ListMeta: obj.(*v1alpha1.CorrectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.CorrectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested corrections.
func (c *FakeCorrections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(correctionsResource, c.ns, opts))

}

// Create takes the representation of a correction and creates it.  Returns the server's representation of the correction, and an error, if there is any.
func (c *FakeCorrections) Create(ctx context.Context, correction *v1alpha1.Correction, opts v1.CreateOptions) (result *v1alpha1.Correction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(correctionsResource, c.ns, correction), &v1alpha1.Correction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Correction), err
}

// Update takes the representation of a correction and updates it. Returns the server's representation of the correction, and an error, if there is any.
func (c *FakeCorrections) Update(ctx context.Context, correction *v1alpha1.Correction, opts v1.UpdateOptions) (result *v1alpha1.Correction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(correctionsResource, c.ns, correction), &v1alpha1.Correction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Correction), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCorrections) UpdateStatus(ctx context.Context, correction *v1alpha1.Correction, opts v1.UpdateOptions) (*v1alpha1.Correction, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(correctionsResource, "status", c.ns, correction), &v1alpha1.Correction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Correction), err
}

// Delete takes name of the correction and deletes it. Returns an error if one occurs.
func (c *FakeCorrections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(correctionsResource, c.ns, name), &v1alpha1.Correction{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCorrections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(correctionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CorrectionList{})
	return err
}

// Patch applies the patch and returns the patched correction.
func (c *FakeCorrections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Correction, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(correctionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Correction{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Correction), err
}
