/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/downtime/v1alpha1"
	scheme "kubeform.dev/provider-datadog-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DowntimesGetter has a method to return a DowntimeInterface.
// A group's client should implement this interface.
type DowntimesGetter interface {
	Downtimes(namespace string) DowntimeInterface
}

// DowntimeInterface has methods to work with Downtime resources.
type DowntimeInterface interface {
	Create(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.CreateOptions) (*v1alpha1.Downtime, error)
	Update(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.UpdateOptions) (*v1alpha1.Downtime, error)
	UpdateStatus(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.UpdateOptions) (*v1alpha1.Downtime, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Downtime, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DowntimeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Downtime, err error)
	DowntimeExpansion
}

// downtimes implements DowntimeInterface
type downtimes struct {
	client rest.Interface
	ns     string
}

// newDowntimes returns a Downtimes
func newDowntimes(c *DowntimeV1alpha1Client, namespace string) *downtimes {
	return &downtimes{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the downtime, and returns the corresponding downtime object, and an error if there is any.
func (c *downtimes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Downtime, err error) {
	result = &v1alpha1.Downtime{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("downtimes").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Downtimes that match those selectors.
func (c *downtimes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DowntimeList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DowntimeList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("downtimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested downtimes.
func (c *downtimes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("downtimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a downtime and creates it.  Returns the server's representation of the downtime, and an error, if there is any.
func (c *downtimes) Create(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.CreateOptions) (result *v1alpha1.Downtime, err error) {
	result = &v1alpha1.Downtime{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("downtimes").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(downtime).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a downtime and updates it. Returns the server's representation of the downtime, and an error, if there is any.
func (c *downtimes) Update(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.UpdateOptions) (result *v1alpha1.Downtime, err error) {
	result = &v1alpha1.Downtime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("downtimes").
		Name(downtime.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(downtime).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *downtimes) UpdateStatus(ctx context.Context, downtime *v1alpha1.Downtime, opts v1.UpdateOptions) (result *v1alpha1.Downtime, err error) {
	result = &v1alpha1.Downtime{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("downtimes").
		Name(downtime.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(downtime).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the downtime and deletes it. Returns an error if one occurs.
func (c *downtimes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("downtimes").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *downtimes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("downtimes").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched downtime.
func (c *downtimes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Downtime, err error) {
	result = &v1alpha1.Downtime{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("downtimes").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
