/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/logs/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIntegrationPipelines implements IntegrationPipelineInterface
type FakeIntegrationPipelines struct {
	Fake *FakeLogsV1alpha1
	ns   string
}

var integrationpipelinesResource = schema.GroupVersionResource{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Resource: "integrationpipelines"}

var integrationpipelinesKind = schema.GroupVersionKind{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Kind: "IntegrationPipeline"}

// Get takes name of the integrationPipeline, and returns the corresponding integrationPipeline object, and an error if there is any.
func (c *FakeIntegrationPipelines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IntegrationPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(integrationpipelinesResource, c.ns, name), &v1alpha1.IntegrationPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationPipeline), err
}

// List takes label and field selectors, and returns the list of IntegrationPipelines that match those selectors.
func (c *FakeIntegrationPipelines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IntegrationPipelineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(integrationpipelinesResource, integrationpipelinesKind, c.ns, opts), &v1alpha1.IntegrationPipelineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IntegrationPipelineList{ListMeta: obj.(*v1alpha1.IntegrationPipelineList).ListMeta}
	for _, item := range obj.(*v1alpha1.IntegrationPipelineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested integrationPipelines.
func (c *FakeIntegrationPipelines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(integrationpipelinesResource, c.ns, opts))

}

// Create takes the representation of a integrationPipeline and creates it.  Returns the server's representation of the integrationPipeline, and an error, if there is any.
func (c *FakeIntegrationPipelines) Create(ctx context.Context, integrationPipeline *v1alpha1.IntegrationPipeline, opts v1.CreateOptions) (result *v1alpha1.IntegrationPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(integrationpipelinesResource, c.ns, integrationPipeline), &v1alpha1.IntegrationPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationPipeline), err
}

// Update takes the representation of a integrationPipeline and updates it. Returns the server's representation of the integrationPipeline, and an error, if there is any.
func (c *FakeIntegrationPipelines) Update(ctx context.Context, integrationPipeline *v1alpha1.IntegrationPipeline, opts v1.UpdateOptions) (result *v1alpha1.IntegrationPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(integrationpipelinesResource, c.ns, integrationPipeline), &v1alpha1.IntegrationPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationPipeline), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIntegrationPipelines) UpdateStatus(ctx context.Context, integrationPipeline *v1alpha1.IntegrationPipeline, opts v1.UpdateOptions) (*v1alpha1.IntegrationPipeline, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(integrationpipelinesResource, "status", c.ns, integrationPipeline), &v1alpha1.IntegrationPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationPipeline), err
}

// Delete takes name of the integrationPipeline and deletes it. Returns an error if one occurs.
func (c *FakeIntegrationPipelines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(integrationpipelinesResource, c.ns, name), &v1alpha1.IntegrationPipeline{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIntegrationPipelines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(integrationpipelinesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IntegrationPipelineList{})
	return err
}

// Patch applies the patch and returns the patched integrationPipeline.
func (c *FakeIntegrationPipelines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IntegrationPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(integrationpipelinesResource, c.ns, name, pt, data, subresources...), &v1alpha1.IntegrationPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IntegrationPipeline), err
}
