/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/logs/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeArchiveOrders implements ArchiveOrderInterface
type FakeArchiveOrders struct {
	Fake *FakeLogsV1alpha1
	ns   string
}

var archiveordersResource = schema.GroupVersionResource{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Resource: "archiveorders"}

var archiveordersKind = schema.GroupVersionKind{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Kind: "ArchiveOrder"}

// Get takes name of the archiveOrder, and returns the corresponding archiveOrder object, and an error if there is any.
func (c *FakeArchiveOrders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ArchiveOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(archiveordersResource, c.ns, name), &v1alpha1.ArchiveOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArchiveOrder), err
}

// List takes label and field selectors, and returns the list of ArchiveOrders that match those selectors.
func (c *FakeArchiveOrders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ArchiveOrderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(archiveordersResource, archiveordersKind, c.ns, opts), &v1alpha1.ArchiveOrderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ArchiveOrderList{ListMeta: obj.(*v1alpha1.ArchiveOrderList).ListMeta}
	for _, item := range obj.(*v1alpha1.ArchiveOrderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested archiveOrders.
func (c *FakeArchiveOrders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(archiveordersResource, c.ns, opts))

}

// Create takes the representation of a archiveOrder and creates it.  Returns the server's representation of the archiveOrder, and an error, if there is any.
func (c *FakeArchiveOrders) Create(ctx context.Context, archiveOrder *v1alpha1.ArchiveOrder, opts v1.CreateOptions) (result *v1alpha1.ArchiveOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(archiveordersResource, c.ns, archiveOrder), &v1alpha1.ArchiveOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArchiveOrder), err
}

// Update takes the representation of a archiveOrder and updates it. Returns the server's representation of the archiveOrder, and an error, if there is any.
func (c *FakeArchiveOrders) Update(ctx context.Context, archiveOrder *v1alpha1.ArchiveOrder, opts v1.UpdateOptions) (result *v1alpha1.ArchiveOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(archiveordersResource, c.ns, archiveOrder), &v1alpha1.ArchiveOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArchiveOrder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeArchiveOrders) UpdateStatus(ctx context.Context, archiveOrder *v1alpha1.ArchiveOrder, opts v1.UpdateOptions) (*v1alpha1.ArchiveOrder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(archiveordersResource, "status", c.ns, archiveOrder), &v1alpha1.ArchiveOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArchiveOrder), err
}

// Delete takes name of the archiveOrder and deletes it. Returns an error if one occurs.
func (c *FakeArchiveOrders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(archiveordersResource, c.ns, name), &v1alpha1.ArchiveOrder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeArchiveOrders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(archiveordersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ArchiveOrderList{})
	return err
}

// Patch applies the patch and returns the patched archiveOrder.
func (c *FakeArchiveOrders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ArchiveOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(archiveordersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ArchiveOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ArchiveOrder), err
}
