/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/logs/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomPipelines implements CustomPipelineInterface
type FakeCustomPipelines struct {
	Fake *FakeLogsV1alpha1
	ns   string
}

var custompipelinesResource = schema.GroupVersionResource{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Resource: "custompipelines"}

var custompipelinesKind = schema.GroupVersionKind{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Kind: "CustomPipeline"}

// Get takes name of the customPipeline, and returns the corresponding customPipeline object, and an error if there is any.
func (c *FakeCustomPipelines) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(custompipelinesResource, c.ns, name), &v1alpha1.CustomPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomPipeline), err
}

// List takes label and field selectors, and returns the list of CustomPipelines that match those selectors.
func (c *FakeCustomPipelines) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomPipelineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(custompipelinesResource, custompipelinesKind, c.ns, opts), &v1alpha1.CustomPipelineList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomPipelineList{ListMeta: obj.(*v1alpha1.CustomPipelineList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomPipelineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customPipelines.
func (c *FakeCustomPipelines) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(custompipelinesResource, c.ns, opts))

}

// Create takes the representation of a customPipeline and creates it.  Returns the server's representation of the customPipeline, and an error, if there is any.
func (c *FakeCustomPipelines) Create(ctx context.Context, customPipeline *v1alpha1.CustomPipeline, opts v1.CreateOptions) (result *v1alpha1.CustomPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(custompipelinesResource, c.ns, customPipeline), &v1alpha1.CustomPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomPipeline), err
}

// Update takes the representation of a customPipeline and updates it. Returns the server's representation of the customPipeline, and an error, if there is any.
func (c *FakeCustomPipelines) Update(ctx context.Context, customPipeline *v1alpha1.CustomPipeline, opts v1.UpdateOptions) (result *v1alpha1.CustomPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(custompipelinesResource, c.ns, customPipeline), &v1alpha1.CustomPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomPipeline), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomPipelines) UpdateStatus(ctx context.Context, customPipeline *v1alpha1.CustomPipeline, opts v1.UpdateOptions) (*v1alpha1.CustomPipeline, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(custompipelinesResource, "status", c.ns, customPipeline), &v1alpha1.CustomPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomPipeline), err
}

// Delete takes name of the customPipeline and deletes it. Returns an error if one occurs.
func (c *FakeCustomPipelines) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(custompipelinesResource, c.ns, name), &v1alpha1.CustomPipeline{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomPipelines) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(custompipelinesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomPipelineList{})
	return err
}

// Patch applies the patch and returns the patched customPipeline.
func (c *FakeCustomPipelines) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomPipeline, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(custompipelinesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomPipeline{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomPipeline), err
}
