/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/logs/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeIndexOrders implements IndexOrderInterface
type FakeIndexOrders struct {
	Fake *FakeLogsV1alpha1
	ns   string
}

var indexordersResource = schema.GroupVersionResource{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Resource: "indexorders"}

var indexordersKind = schema.GroupVersionKind{Group: "logs.datadog.kubeform.com", Version: "v1alpha1", Kind: "IndexOrder"}

// Get takes name of the indexOrder, and returns the corresponding indexOrder object, and an error if there is any.
func (c *FakeIndexOrders) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.IndexOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(indexordersResource, c.ns, name), &v1alpha1.IndexOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndexOrder), err
}

// List takes label and field selectors, and returns the list of IndexOrders that match those selectors.
func (c *FakeIndexOrders) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.IndexOrderList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(indexordersResource, indexordersKind, c.ns, opts), &v1alpha1.IndexOrderList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.IndexOrderList{ListMeta: obj.(*v1alpha1.IndexOrderList).ListMeta}
	for _, item := range obj.(*v1alpha1.IndexOrderList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested indexOrders.
func (c *FakeIndexOrders) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(indexordersResource, c.ns, opts))

}

// Create takes the representation of a indexOrder and creates it.  Returns the server's representation of the indexOrder, and an error, if there is any.
func (c *FakeIndexOrders) Create(ctx context.Context, indexOrder *v1alpha1.IndexOrder, opts v1.CreateOptions) (result *v1alpha1.IndexOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(indexordersResource, c.ns, indexOrder), &v1alpha1.IndexOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndexOrder), err
}

// Update takes the representation of a indexOrder and updates it. Returns the server's representation of the indexOrder, and an error, if there is any.
func (c *FakeIndexOrders) Update(ctx context.Context, indexOrder *v1alpha1.IndexOrder, opts v1.UpdateOptions) (result *v1alpha1.IndexOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(indexordersResource, c.ns, indexOrder), &v1alpha1.IndexOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndexOrder), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeIndexOrders) UpdateStatus(ctx context.Context, indexOrder *v1alpha1.IndexOrder, opts v1.UpdateOptions) (*v1alpha1.IndexOrder, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(indexordersResource, "status", c.ns, indexOrder), &v1alpha1.IndexOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndexOrder), err
}

// Delete takes name of the indexOrder and deletes it. Returns an error if one occurs.
func (c *FakeIndexOrders) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(indexordersResource, c.ns, name), &v1alpha1.IndexOrder{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeIndexOrders) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(indexordersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.IndexOrderList{})
	return err
}

// Patch applies the patch and returns the patched indexOrder.
func (c *FakeIndexOrders) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.IndexOrder, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(indexordersResource, c.ns, name, pt, data, subresources...), &v1alpha1.IndexOrder{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.IndexOrder), err
}
