/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GlobalVariableListerExpansion allows custom methods to be added to
// GlobalVariableLister.
type GlobalVariableListerExpansion interface{}

// GlobalVariableNamespaceListerExpansion allows custom methods to be added to
// GlobalVariableNamespaceLister.
type GlobalVariableNamespaceListerExpansion interface{}

// PrivateLocationListerExpansion allows custom methods to be added to
// PrivateLocationLister.
type PrivateLocationListerExpansion interface{}

// PrivateLocationNamespaceListerExpansion allows custom methods to be added to
// PrivateLocationNamespaceLister.
type PrivateLocationNamespaceListerExpansion interface{}

// SyntheticstestListerExpansion allows custom methods to be added to
// SyntheticstestLister.
type SyntheticstestListerExpansion interface{}

// SyntheticstestNamespaceListerExpansion allows custom methods to be added to
// SyntheticstestNamespaceLister.
type SyntheticstestNamespaceListerExpansion interface{}
