/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/webhook/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomVariables implements CustomVariableInterface
type FakeCustomVariables struct {
	Fake *FakeWebhookV1alpha1
	ns   string
}

var customvariablesResource = schema.GroupVersionResource{Group: "webhook.datadog.kubeform.com", Version: "v1alpha1", Resource: "customvariables"}

var customvariablesKind = schema.GroupVersionKind{Group: "webhook.datadog.kubeform.com", Version: "v1alpha1", Kind: "CustomVariable"}

// Get takes name of the customVariable, and returns the corresponding customVariable object, and an error if there is any.
func (c *FakeCustomVariables) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomVariable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customvariablesResource, c.ns, name), &v1alpha1.CustomVariable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomVariable), err
}

// List takes label and field selectors, and returns the list of CustomVariables that match those selectors.
func (c *FakeCustomVariables) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomVariableList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customvariablesResource, customvariablesKind, c.ns, opts), &v1alpha1.CustomVariableList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomVariableList{ListMeta: obj.(*v1alpha1.CustomVariableList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomVariableList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customVariables.
func (c *FakeCustomVariables) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customvariablesResource, c.ns, opts))

}

// Create takes the representation of a customVariable and creates it.  Returns the server's representation of the customVariable, and an error, if there is any.
func (c *FakeCustomVariables) Create(ctx context.Context, customVariable *v1alpha1.CustomVariable, opts v1.CreateOptions) (result *v1alpha1.CustomVariable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customvariablesResource, c.ns, customVariable), &v1alpha1.CustomVariable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomVariable), err
}

// Update takes the representation of a customVariable and updates it. Returns the server's representation of the customVariable, and an error, if there is any.
func (c *FakeCustomVariables) Update(ctx context.Context, customVariable *v1alpha1.CustomVariable, opts v1.UpdateOptions) (result *v1alpha1.CustomVariable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customvariablesResource, c.ns, customVariable), &v1alpha1.CustomVariable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomVariable), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomVariables) UpdateStatus(ctx context.Context, customVariable *v1alpha1.CustomVariable, opts v1.UpdateOptions) (*v1alpha1.CustomVariable, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(customvariablesResource, "status", c.ns, customVariable), &v1alpha1.CustomVariable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomVariable), err
}

// Delete takes name of the customVariable and deletes it. Returns an error if one occurs.
func (c *FakeCustomVariables) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customvariablesResource, c.ns, name), &v1alpha1.CustomVariable{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomVariables) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customvariablesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomVariableList{})
	return err
}

// Patch applies the patch and returns the patched customVariable.
func (c *FakeCustomVariables) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomVariable, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customvariablesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomVariable{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomVariable), err
}
