/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	clientset "kubeform.dev/provider-datadog-api/client/clientset/versioned"
	dashboardv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/dashboard/v1alpha1"
	fakedashboardv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/dashboard/v1alpha1/fake"
	downtimev1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/downtime/v1alpha1"
	fakedowntimev1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/downtime/v1alpha1/fake"
	integrationv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/integration/v1alpha1"
	fakeintegrationv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/integration/v1alpha1/fake"
	logsv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/logs/v1alpha1"
	fakelogsv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/logs/v1alpha1/fake"
	metricv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/metric/v1alpha1"
	fakemetricv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/metric/v1alpha1/fake"
	monitorv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/monitor/v1alpha1"
	fakemonitorv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/monitor/v1alpha1/fake"
	rolev1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/role/v1alpha1"
	fakerolev1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/role/v1alpha1/fake"
	securityv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/security/v1alpha1"
	fakesecurityv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/security/v1alpha1/fake"
	servicev1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/service/v1alpha1"
	fakeservicev1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/service/v1alpha1/fake"
	slov1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/slo/v1alpha1"
	fakeslov1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/slo/v1alpha1/fake"
	syntheticsv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/synthetics/v1alpha1"
	fakesyntheticsv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/synthetics/v1alpha1/fake"
	syntheticstestv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/syntheticstest/v1alpha1"
	fakesyntheticstestv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/syntheticstest/v1alpha1/fake"
	userv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/user/v1alpha1"
	fakeuserv1alpha1 "kubeform.dev/provider-datadog-api/client/clientset/versioned/typed/user/v1alpha1/fake"

	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	"k8s.io/client-go/discovery"
	fakediscovery "k8s.io/client-go/discovery/fake"
	"k8s.io/client-go/testing"
)

// NewSimpleClientset returns a clientset that will respond with the provided objects.
// It's backed by a very simple object tracker that processes creates, updates and deletions as-is,
// without applying any validations and/or defaults. It shouldn't be considered a replacement
// for a real clientset and is mostly useful in simple unit tests.
func NewSimpleClientset(objects ...runtime.Object) *Clientset {
	o := testing.NewObjectTracker(scheme, codecs.UniversalDecoder())
	for _, obj := range objects {
		if err := o.Add(obj); err != nil {
			panic(err)
		}
	}

	cs := &Clientset{tracker: o}
	cs.discovery = &fakediscovery.FakeDiscovery{Fake: &cs.Fake}
	cs.AddReactor("*", "*", testing.ObjectReaction(o))
	cs.AddWatchReactor("*", func(action testing.Action) (handled bool, ret watch.Interface, err error) {
		gvr := action.GetResource()
		ns := action.GetNamespace()
		watch, err := o.Watch(gvr, ns)
		if err != nil {
			return false, nil, err
		}
		return true, watch, nil
	})

	return cs
}

// Clientset implements clientset.Interface. Meant to be embedded into a
// struct to get a default implementation. This makes faking out just the method
// you want to test easier.
type Clientset struct {
	testing.Fake
	discovery *fakediscovery.FakeDiscovery
	tracker   testing.ObjectTracker
}

func (c *Clientset) Discovery() discovery.DiscoveryInterface {
	return c.discovery
}

func (c *Clientset) Tracker() testing.ObjectTracker {
	return c.tracker
}

var _ clientset.Interface = &Clientset{}

// DashboardV1alpha1 retrieves the DashboardV1alpha1Client
func (c *Clientset) DashboardV1alpha1() dashboardv1alpha1.DashboardV1alpha1Interface {
	return &fakedashboardv1alpha1.FakeDashboardV1alpha1{Fake: &c.Fake}
}

// DowntimeV1alpha1 retrieves the DowntimeV1alpha1Client
func (c *Clientset) DowntimeV1alpha1() downtimev1alpha1.DowntimeV1alpha1Interface {
	return &fakedowntimev1alpha1.FakeDowntimeV1alpha1{Fake: &c.Fake}
}

// IntegrationV1alpha1 retrieves the IntegrationV1alpha1Client
func (c *Clientset) IntegrationV1alpha1() integrationv1alpha1.IntegrationV1alpha1Interface {
	return &fakeintegrationv1alpha1.FakeIntegrationV1alpha1{Fake: &c.Fake}
}

// LogsV1alpha1 retrieves the LogsV1alpha1Client
func (c *Clientset) LogsV1alpha1() logsv1alpha1.LogsV1alpha1Interface {
	return &fakelogsv1alpha1.FakeLogsV1alpha1{Fake: &c.Fake}
}

// MetricV1alpha1 retrieves the MetricV1alpha1Client
func (c *Clientset) MetricV1alpha1() metricv1alpha1.MetricV1alpha1Interface {
	return &fakemetricv1alpha1.FakeMetricV1alpha1{Fake: &c.Fake}
}

// MonitorV1alpha1 retrieves the MonitorV1alpha1Client
func (c *Clientset) MonitorV1alpha1() monitorv1alpha1.MonitorV1alpha1Interface {
	return &fakemonitorv1alpha1.FakeMonitorV1alpha1{Fake: &c.Fake}
}

// RoleV1alpha1 retrieves the RoleV1alpha1Client
func (c *Clientset) RoleV1alpha1() rolev1alpha1.RoleV1alpha1Interface {
	return &fakerolev1alpha1.FakeRoleV1alpha1{Fake: &c.Fake}
}

// SecurityV1alpha1 retrieves the SecurityV1alpha1Client
func (c *Clientset) SecurityV1alpha1() securityv1alpha1.SecurityV1alpha1Interface {
	return &fakesecurityv1alpha1.FakeSecurityV1alpha1{Fake: &c.Fake}
}

// ServiceV1alpha1 retrieves the ServiceV1alpha1Client
func (c *Clientset) ServiceV1alpha1() servicev1alpha1.ServiceV1alpha1Interface {
	return &fakeservicev1alpha1.FakeServiceV1alpha1{Fake: &c.Fake}
}

// SloV1alpha1 retrieves the SloV1alpha1Client
func (c *Clientset) SloV1alpha1() slov1alpha1.SloV1alpha1Interface {
	return &fakeslov1alpha1.FakeSloV1alpha1{Fake: &c.Fake}
}

// SyntheticsV1alpha1 retrieves the SyntheticsV1alpha1Client
func (c *Clientset) SyntheticsV1alpha1() syntheticsv1alpha1.SyntheticsV1alpha1Interface {
	return &fakesyntheticsv1alpha1.FakeSyntheticsV1alpha1{Fake: &c.Fake}
}

// SyntheticstestV1alpha1 retrieves the SyntheticstestV1alpha1Client
func (c *Clientset) SyntheticstestV1alpha1() syntheticstestv1alpha1.SyntheticstestV1alpha1Interface {
	return &fakesyntheticstestv1alpha1.FakeSyntheticstestV1alpha1{Fake: &c.Fake}
}

// UserV1alpha1 retrieves the UserV1alpha1Client
func (c *Clientset) UserV1alpha1() userv1alpha1.UserV1alpha1Interface {
	return &fakeuserv1alpha1.FakeUserV1alpha1{Fake: &c.Fake}
}
