/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/integration/v1alpha1"
	scheme "kubeform.dev/provider-datadog-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AwsLogCollectionsGetter has a method to return a AwsLogCollectionInterface.
// A group's client should implement this interface.
type AwsLogCollectionsGetter interface {
	AwsLogCollections(namespace string) AwsLogCollectionInterface
}

// AwsLogCollectionInterface has methods to work with AwsLogCollection resources.
type AwsLogCollectionInterface interface {
	Create(ctx context.Context, awsLogCollection *v1alpha1.AwsLogCollection, opts v1.CreateOptions) (*v1alpha1.AwsLogCollection, error)
	Update(ctx context.Context, awsLogCollection *v1alpha1.AwsLogCollection, opts v1.UpdateOptions) (*v1alpha1.AwsLogCollection, error)
	UpdateStatus(ctx context.Context, awsLogCollection *v1alpha1.AwsLogCollection, opts v1.UpdateOptions) (*v1alpha1.AwsLogCollection, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.AwsLogCollection, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.AwsLogCollectionList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AwsLogCollection, err error)
	AwsLogCollectionExpansion
}

// awsLogCollections implements AwsLogCollectionInterface
type awsLogCollections struct {
	client rest.Interface
	ns     string
}

// newAwsLogCollections returns a AwsLogCollections
func newAwsLogCollections(c *IntegrationV1alpha1Client, namespace string) *awsLogCollections {
	return &awsLogCollections{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the awsLogCollection, and returns the corresponding awsLogCollection object, and an error if there is any.
func (c *awsLogCollections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AwsLogCollection, err error) {
	result = &v1alpha1.AwsLogCollection{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awslogcollections").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AwsLogCollections that match those selectors.
func (c *awsLogCollections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AwsLogCollectionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AwsLogCollectionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("awslogcollections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested awsLogCollections.
func (c *awsLogCollections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("awslogcollections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a awsLogCollection and creates it.  Returns the server's representation of the awsLogCollection, and an error, if there is any.
func (c *awsLogCollections) Create(ctx context.Context, awsLogCollection *v1alpha1.AwsLogCollection, opts v1.CreateOptions) (result *v1alpha1.AwsLogCollection, err error) {
	result = &v1alpha1.AwsLogCollection{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("awslogcollections").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(awsLogCollection).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a awsLogCollection and updates it. Returns the server's representation of the awsLogCollection, and an error, if there is any.
func (c *awsLogCollections) Update(ctx context.Context, awsLogCollection *v1alpha1.AwsLogCollection, opts v1.UpdateOptions) (result *v1alpha1.AwsLogCollection, err error) {
	result = &v1alpha1.AwsLogCollection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awslogcollections").
		Name(awsLogCollection.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(awsLogCollection).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *awsLogCollections) UpdateStatus(ctx context.Context, awsLogCollection *v1alpha1.AwsLogCollection, opts v1.UpdateOptions) (result *v1alpha1.AwsLogCollection, err error) {
	result = &v1alpha1.AwsLogCollection{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("awslogcollections").
		Name(awsLogCollection.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(awsLogCollection).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the awsLogCollection and deletes it. Returns an error if one occurs.
func (c *awsLogCollections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awslogcollections").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *awsLogCollections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("awslogcollections").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched awsLogCollection.
func (c *awsLogCollections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AwsLogCollection, err error) {
	result = &v1alpha1.AwsLogCollection{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("awslogcollections").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
