apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: datadog.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: organizations.child.datadog.kubeform.com
spec:
  group: child.datadog.kubeform.com
  names:
    kind: Organization
    listKind: OrganizationList
    plural: organizations
    singular: organization
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  apiKey:
                    description: Datadog API key.
                    items:
                      properties:
                        name:
                          description: Name of your API key.
                          type: string
                      type: object
                    type: array
                  applicationKey:
                    description: An application key with its associated metadata.
                    items:
                      properties:
                        name:
                          description: Name of an application key.
                          type: string
                        owner:
                          description: Owner of an application key.
                          type: string
                      type: object
                    type: array
                  description:
                    description: Description of the organization.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name for Child Organization after creation.
                    type: string
                  publicID:
                    description: The `public_id` of the organization you are operating
                      within.
                    type: string
                  settings:
                    description: Organization settings
                    items:
                      properties:
                        privateWidgetShare:
                          description: Whether or not the organization users can share
                            widgets outside of Datadog.
                          type: boolean
                        saml:
                          description: SAML properties
                          items:
                            properties:
                              enabled:
                                description: Whether or not SAML is enabled for this
                                  organization.
                                type: boolean
                            type: object
                          type: array
                        samlAutocreateAccessRole:
                          description: 'The access role of the user. Options are `st`
                            (standard user), `adm` (admin user), or `ro` (read-only
                            user). Allowed enum values: `st`, `adm` , `ro`, `ERROR`'
                          type: string
                        samlAutocreateUsersDomains:
                          description: List of domains where the SAML automated user
                            creation is enabled.
                          items:
                            properties:
                              domains:
                                description: List of domains where the SAML automated
                                  user creation is enabled.
                                items:
                                  type: string
                                type: array
                              enabled:
                                description: Whether or not the automated user creation
                                  based on SAML domain is enabled.
                                type: boolean
                            type: object
                          type: array
                        samlCanBeEnabled:
                          description: Whether or not SAML can be enabled for this
                            organization.
                          type: boolean
                        samlIdpEndpoint:
                          description: Identity provider endpoint for SAML authentication.
                          type: string
                        samlIdpInitiatedLogin:
                          description: Whether or not a SAML identity provider metadata
                            file was provided to the Datadog organization.
                          items:
                            properties:
                              enabled:
                                description: Whether or not a SAML identity provider
                                  metadata file was provided to the Datadog organization.
                                type: boolean
                            type: object
                          type: array
                        samlIdpMetadataUploaded:
                          description: Whether or not a SAML identity provider metadata
                            file was provided to the Datadog organization.
                          type: boolean
                        samlLoginURL:
                          description: URL for SAML logging.
                          type: string
                        samlStrictMode:
                          description: Whether or not the SAML strict mode is enabled.
                            If true, all users must log in with SAML.
                          items:
                            properties:
                              enabled:
                                description: Whether or not the SAML strict mode is
                                  enabled. If true, all users must log in with SAML.
                                type: boolean
                            type: object
                          type: array
                      type: object
                    type: array
                  user:
                    description: Information about a user
                    items:
                      properties:
                        accessRole:
                          description: 'The access role of the user. Options are `st`
                            (standard user), `adm` (admin user), or `ro` (read-only
                            user). Allowed enum values: `st`, `adm`, `ro`, `ERROR`'
                          type: string
                        email:
                          description: The new email of the user.
                          type: string
                        name:
                          description: The name of the user.
                          type: string
                      type: object
                    type: array
                required:
                - name
                type: object
              secretRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              state:
                properties:
                  apiKey:
                    description: Datadog API key.
                    items:
                      properties:
                        name:
                          description: Name of your API key.
                          type: string
                      type: object
                    type: array
                  applicationKey:
                    description: An application key with its associated metadata.
                    items:
                      properties:
                        name:
                          description: Name of an application key.
                          type: string
                        owner:
                          description: Owner of an application key.
                          type: string
                      type: object
                    type: array
                  description:
                    description: Description of the organization.
                    type: string
                  id:
                    type: string
                  name:
                    description: Name for Child Organization after creation.
                    type: string
                  publicID:
                    description: The `public_id` of the organization you are operating
                      within.
                    type: string
                  settings:
                    description: Organization settings
                    items:
                      properties:
                        privateWidgetShare:
                          description: Whether or not the organization users can share
                            widgets outside of Datadog.
                          type: boolean
                        saml:
                          description: SAML properties
                          items:
                            properties:
                              enabled:
                                description: Whether or not SAML is enabled for this
                                  organization.
                                type: boolean
                            type: object
                          type: array
                        samlAutocreateAccessRole:
                          description: 'The access role of the user. Options are `st`
                            (standard user), `adm` (admin user), or `ro` (read-only
                            user). Allowed enum values: `st`, `adm` , `ro`, `ERROR`'
                          type: string
                        samlAutocreateUsersDomains:
                          description: List of domains where the SAML automated user
                            creation is enabled.
                          items:
                            properties:
                              domains:
                                description: List of domains where the SAML automated
                                  user creation is enabled.
                                items:
                                  type: string
                                type: array
                              enabled:
                                description: Whether or not the automated user creation
                                  based on SAML domain is enabled.
                                type: boolean
                            type: object
                          type: array
                        samlCanBeEnabled:
                          description: Whether or not SAML can be enabled for this
                            organization.
                          type: boolean
                        samlIdpEndpoint:
                          description: Identity provider endpoint for SAML authentication.
                          type: string
                        samlIdpInitiatedLogin:
                          description: Whether or not a SAML identity provider metadata
                            file was provided to the Datadog organization.
                          items:
                            properties:
                              enabled:
                                description: Whether or not a SAML identity provider
                                  metadata file was provided to the Datadog organization.
                                type: boolean
                            type: object
                          type: array
                        samlIdpMetadataUploaded:
                          description: Whether or not a SAML identity provider metadata
                            file was provided to the Datadog organization.
                          type: boolean
                        samlLoginURL:
                          description: URL for SAML logging.
                          type: string
                        samlStrictMode:
                          description: Whether or not the SAML strict mode is enabled.
                            If true, all users must log in with SAML.
                          items:
                            properties:
                              enabled:
                                description: Whether or not the SAML strict mode is
                                  enabled. If true, all users must log in with SAML.
                                type: boolean
                            type: object
                          type: array
                      type: object
                    type: array
                  user:
                    description: Information about a user
                    items:
                      properties:
                        accessRole:
                          description: 'The access role of the user. Options are `st`
                            (standard user), `adm` (admin user), or `ro` (read-only
                            user). Allowed enum values: `st`, `adm`, `ro`, `ERROR`'
                          type: string
                        email:
                          description: The new email of the user.
                          type: string
                        name:
                          description: The name of the user.
                          type: string
                      type: object
                    type: array
                required:
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
