apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: datadog.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: indices.logs.datadog.kubeform.com
spec:
  group: logs.datadog.kubeform.com
  names:
    kind: Index
    listKind: IndexList
    plural: indices
    singular: index
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  dailyLimit:
                    description: The number of log events you can send in this index
                      per day before you are rate-limited.
                    format: int64
                    type: integer
                  disableDailyLimit:
                    description: If true, sets the daily_limit value to null and the
                      index is not limited on a daily basis (any specified daily_limit
                      value in the request is ignored). If false or omitted, the index's
                      current daily_limit is maintained.
                    type: boolean
                  exclusionFilter:
                    description: List of exclusion filters.
                    items:
                      properties:
                        filter:
                          items:
                            properties:
                              query:
                                description: Only logs matching the filter criteria
                                  and the query of the parent index will be considered
                                  for this exclusion filter.
                                type: string
                              sampleRate:
                                description: The fraction of logs excluded by the
                                  exclusion filter, when active.
                                format: double
                                type: number
                            type: object
                          type: array
                        isEnabled:
                          description: A boolean stating if the exclusion is active
                            or not.
                          type: boolean
                        name:
                          description: The name of the exclusion filter.
                          type: string
                      type: object
                    type: array
                  filter:
                    description: Logs filter
                    items:
                      properties:
                        query:
                          description: Logs filter criteria. Only logs matching this
                            filter criteria are considered for this index.
                          type: string
                      required:
                      - query
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: The name of the index.
                    type: string
                  retentionDays:
                    description: The number of days before logs are deleted from this
                      index.
                    format: int64
                    type: integer
                required:
                - filter
                - name
                type: object
              state:
                properties:
                  dailyLimit:
                    description: The number of log events you can send in this index
                      per day before you are rate-limited.
                    format: int64
                    type: integer
                  disableDailyLimit:
                    description: If true, sets the daily_limit value to null and the
                      index is not limited on a daily basis (any specified daily_limit
                      value in the request is ignored). If false or omitted, the index's
                      current daily_limit is maintained.
                    type: boolean
                  exclusionFilter:
                    description: List of exclusion filters.
                    items:
                      properties:
                        filter:
                          items:
                            properties:
                              query:
                                description: Only logs matching the filter criteria
                                  and the query of the parent index will be considered
                                  for this exclusion filter.
                                type: string
                              sampleRate:
                                description: The fraction of logs excluded by the
                                  exclusion filter, when active.
                                format: double
                                type: number
                            type: object
                          type: array
                        isEnabled:
                          description: A boolean stating if the exclusion is active
                            or not.
                          type: boolean
                        name:
                          description: The name of the exclusion filter.
                          type: string
                      type: object
                    type: array
                  filter:
                    description: Logs filter
                    items:
                      properties:
                        query:
                          description: Logs filter criteria. Only logs matching this
                            filter criteria are considered for this index.
                          type: string
                      required:
                      - query
                      type: object
                    type: array
                  id:
                    type: string
                  name:
                    description: The name of the index.
                    type: string
                  retentionDays:
                    description: The number of days before logs are deleted from this
                      index.
                    format: int64
                    type: integer
                required:
                - filter
                - name
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
