apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: datadog.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: levelobjectives.service.datadog.kubeform.com
spec:
  group: service.datadog.kubeform.com
  names:
    kind: LevelObjective
    listKind: LevelObjectiveList
    plural: levelobjectives
    singular: levelobjective
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  description:
                    description: A description of this service level objective.
                    type: string
                  forceDelete:
                    description: A boolean indicating whether this monitor can be
                      deleted even if it’s referenced by other resources (e.g. dashboards).
                    type: boolean
                  groups:
                    description: A static set of groups to filter monitor-based SLOs
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  monitorIDS:
                    description: A static set of monitor IDs to use as part of the
                      SLO
                    items:
                      format: int64
                      type: integer
                    type: array
                  name:
                    description: Name of Datadog service level objective
                    type: string
                  query:
                    description: The metric query of good / total events
                    properties:
                      denominator:
                        description: The sum of the `total` events.
                        type: string
                      numerator:
                        description: The sum of all the `good` events.
                        type: string
                    required:
                    - denominator
                    - numerator
                    type: object
                  tags:
                    description: 'A list of tags to associate with your service level
                      objective. This can help you categorize and filter service level
                      objectives in the service level objectives page of the UI. Note:
                      it''s not currently possible to filter by these tags when querying
                      via the API'
                    items:
                      type: string
                    type: array
                  thresholds:
                    description: A list of thresholds and targets that define the
                      service level objectives from the provided SLIs.
                    items:
                      properties:
                        target:
                          description: The objective's target in`[0,100]`.
                          format: double
                          type: number
                        targetDisplay:
                          description: A string representation of the target that
                            indicates its precision. It uses trailing zeros to show
                            significant decimal places (e.g. `98.00`).
                          type: string
                        timeframe:
                          description: The time frame for the objective. The mapping
                            from these types to the types found in the Datadog Web
                            UI can be found in the Datadog API documentation page.
                          type: string
                        warning:
                          description: The objective's warning value in `[0,100]`.
                            This must be greater than the target value.
                          format: double
                          type: number
                        warningDisplay:
                          description: A string representation of the warning target
                            (see the description of the target_display field for details).
                          type: string
                      required:
                      - target
                      - timeframe
                      type: object
                    type: array
                  type:
                    description: The type of the service level objective. The mapping
                      from these types to the types found in the Datadog Web UI can
                      be found in the Datadog API [documentation page](https://docs.datadoghq.com/api/v1/service-level-objectives/#create-a-slo-object).
                    type: string
                  validate:
                    description: Whether or not to validate the SLO.
                    type: boolean
                required:
                - name
                - thresholds
                - type
                type: object
              state:
                properties:
                  description:
                    description: A description of this service level objective.
                    type: string
                  forceDelete:
                    description: A boolean indicating whether this monitor can be
                      deleted even if it’s referenced by other resources (e.g. dashboards).
                    type: boolean
                  groups:
                    description: A static set of groups to filter monitor-based SLOs
                    items:
                      type: string
                    type: array
                  id:
                    type: string
                  monitorIDS:
                    description: A static set of monitor IDs to use as part of the
                      SLO
                    items:
                      format: int64
                      type: integer
                    type: array
                  name:
                    description: Name of Datadog service level objective
                    type: string
                  query:
                    description: The metric query of good / total events
                    properties:
                      denominator:
                        description: The sum of the `total` events.
                        type: string
                      numerator:
                        description: The sum of all the `good` events.
                        type: string
                    required:
                    - denominator
                    - numerator
                    type: object
                  tags:
                    description: 'A list of tags to associate with your service level
                      objective. This can help you categorize and filter service level
                      objectives in the service level objectives page of the UI. Note:
                      it''s not currently possible to filter by these tags when querying
                      via the API'
                    items:
                      type: string
                    type: array
                  thresholds:
                    description: A list of thresholds and targets that define the
                      service level objectives from the provided SLIs.
                    items:
                      properties:
                        target:
                          description: The objective's target in`[0,100]`.
                          format: double
                          type: number
                        targetDisplay:
                          description: A string representation of the target that
                            indicates its precision. It uses trailing zeros to show
                            significant decimal places (e.g. `98.00`).
                          type: string
                        timeframe:
                          description: The time frame for the objective. The mapping
                            from these types to the types found in the Datadog Web
                            UI can be found in the Datadog API documentation page.
                          type: string
                        warning:
                          description: The objective's warning value in `[0,100]`.
                            This must be greater than the target value.
                          format: double
                          type: number
                        warningDisplay:
                          description: A string representation of the warning target
                            (see the description of the target_display field for details).
                          type: string
                      required:
                      - target
                      - timeframe
                      type: object
                    type: array
                  type:
                    description: The type of the service level objective. The mapping
                      from these types to the types found in the Datadog Web UI can
                      be found in the Datadog API [documentation page](https://docs.datadoghq.com/api/v1/service-level-objectives/#create-a-slo-object).
                    type: string
                  validate:
                    description: Whether or not to validate the SLO.
                    type: boolean
                required:
                - name
                - thresholds
                - type
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
