apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: datadog.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: corrections.slo.datadog.kubeform.com
spec:
  group: slo.datadog.kubeform.com
  names:
    kind: Correction
    listKind: CorrectionList
    plural: corrections
    singular: correction
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  category:
                    description: Category the SLO correction belongs to.
                    type: string
                  description:
                    description: Description of the correction being made.
                    type: string
                  duration:
                    description: Length of time in seconds for a specified `rrule`
                      recurring SLO correction (required if specifying `rrule`)
                    format: int64
                    type: integer
                  end:
                    description: Ending time of the correction in epoch seconds. Required
                      for one time corrections, but optional if `rrule` is specified
                    format: int64
                    type: integer
                  id:
                    type: string
                  rrule:
                    description: Recurrence rules as defined in the iCalendar RFC
                      5545. Supported rules for SLO corrections are `FREQ`, `INTERVAL`,
                      `COUNT` and `UNTIL`.
                    type: string
                  sloID:
                    description: ID of the SLO that this correction will be applied
                      to.
                    type: string
                  start:
                    description: Starting time of the correction in epoch seconds.
                    format: int64
                    type: integer
                  timezone:
                    description: The timezone to display in the UI for the correction
                      times (defaults to "UTC")
                    type: string
                required:
                - category
                - sloID
                - start
                type: object
              state:
                properties:
                  category:
                    description: Category the SLO correction belongs to.
                    type: string
                  description:
                    description: Description of the correction being made.
                    type: string
                  duration:
                    description: Length of time in seconds for a specified `rrule`
                      recurring SLO correction (required if specifying `rrule`)
                    format: int64
                    type: integer
                  end:
                    description: Ending time of the correction in epoch seconds. Required
                      for one time corrections, but optional if `rrule` is specified
                    format: int64
                    type: integer
                  id:
                    type: string
                  rrule:
                    description: Recurrence rules as defined in the iCalendar RFC
                      5545. Supported rules for SLO corrections are `FREQ`, `INTERVAL`,
                      `COUNT` and `UNTIL`.
                    type: string
                  sloID:
                    description: ID of the SLO that this correction will be applied
                      to.
                    type: string
                  start:
                    description: Starting time of the correction in epoch seconds.
                    format: int64
                    type: integer
                  timezone:
                    description: The timezone to display in the UI for the correction
                      times (defaults to "UTC")
                    type: string
                required:
                - category
                - sloID
                - start
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
