/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/security/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMonitoringRules implements MonitoringRuleInterface
type FakeMonitoringRules struct {
	Fake *FakeSecurityV1alpha1
	ns   string
}

var monitoringrulesResource = schema.GroupVersionResource{Group: "security.datadog.kubeform.com", Version: "v1alpha1", Resource: "monitoringrules"}

var monitoringrulesKind = schema.GroupVersionKind{Group: "security.datadog.kubeform.com", Version: "v1alpha1", Kind: "MonitoringRule"}

// Get takes name of the monitoringRule, and returns the corresponding monitoringRule object, and an error if there is any.
func (c *FakeMonitoringRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MonitoringRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(monitoringrulesResource, c.ns, name), &v1alpha1.MonitoringRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringRule), err
}

// List takes label and field selectors, and returns the list of MonitoringRules that match those selectors.
func (c *FakeMonitoringRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MonitoringRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(monitoringrulesResource, monitoringrulesKind, c.ns, opts), &v1alpha1.MonitoringRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MonitoringRuleList{ListMeta: obj.(*v1alpha1.MonitoringRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.MonitoringRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested monitoringRules.
func (c *FakeMonitoringRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(monitoringrulesResource, c.ns, opts))

}

// Create takes the representation of a monitoringRule and creates it.  Returns the server's representation of the monitoringRule, and an error, if there is any.
func (c *FakeMonitoringRules) Create(ctx context.Context, monitoringRule *v1alpha1.MonitoringRule, opts v1.CreateOptions) (result *v1alpha1.MonitoringRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(monitoringrulesResource, c.ns, monitoringRule), &v1alpha1.MonitoringRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringRule), err
}

// Update takes the representation of a monitoringRule and updates it. Returns the server's representation of the monitoringRule, and an error, if there is any.
func (c *FakeMonitoringRules) Update(ctx context.Context, monitoringRule *v1alpha1.MonitoringRule, opts v1.UpdateOptions) (result *v1alpha1.MonitoringRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(monitoringrulesResource, c.ns, monitoringRule), &v1alpha1.MonitoringRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMonitoringRules) UpdateStatus(ctx context.Context, monitoringRule *v1alpha1.MonitoringRule, opts v1.UpdateOptions) (*v1alpha1.MonitoringRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(monitoringrulesResource, "status", c.ns, monitoringRule), &v1alpha1.MonitoringRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringRule), err
}

// Delete takes name of the monitoringRule and deletes it. Returns an error if one occurs.
func (c *FakeMonitoringRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(monitoringrulesResource, c.ns, name), &v1alpha1.MonitoringRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMonitoringRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(monitoringrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MonitoringRuleList{})
	return err
}

// Patch applies the patch and returns the patched monitoringRule.
func (c *FakeMonitoringRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MonitoringRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(monitoringrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MonitoringRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MonitoringRule), err
}
