/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/synthetics/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSyntheticstests implements SyntheticstestInterface
type FakeSyntheticstests struct {
	Fake *FakeSyntheticsV1alpha1
	ns   string
}

var syntheticstestsResource = schema.GroupVersionResource{Group: "synthetics.datadog.kubeform.com", Version: "v1alpha1", Resource: "syntheticstests"}

var syntheticstestsKind = schema.GroupVersionKind{Group: "synthetics.datadog.kubeform.com", Version: "v1alpha1", Kind: "Syntheticstest"}

// Get takes name of the syntheticstest, and returns the corresponding syntheticstest object, and an error if there is any.
func (c *FakeSyntheticstests) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Syntheticstest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(syntheticstestsResource, c.ns, name), &v1alpha1.Syntheticstest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Syntheticstest), err
}

// List takes label and field selectors, and returns the list of Syntheticstests that match those selectors.
func (c *FakeSyntheticstests) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SyntheticstestList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(syntheticstestsResource, syntheticstestsKind, c.ns, opts), &v1alpha1.SyntheticstestList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SyntheticstestList{ListMeta: obj.(*v1alpha1.SyntheticstestList).ListMeta}
	for _, item := range obj.(*v1alpha1.SyntheticstestList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested syntheticstests.
func (c *FakeSyntheticstests) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(syntheticstestsResource, c.ns, opts))

}

// Create takes the representation of a syntheticstest and creates it.  Returns the server's representation of the syntheticstest, and an error, if there is any.
func (c *FakeSyntheticstests) Create(ctx context.Context, syntheticstest *v1alpha1.Syntheticstest, opts v1.CreateOptions) (result *v1alpha1.Syntheticstest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(syntheticstestsResource, c.ns, syntheticstest), &v1alpha1.Syntheticstest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Syntheticstest), err
}

// Update takes the representation of a syntheticstest and updates it. Returns the server's representation of the syntheticstest, and an error, if there is any.
func (c *FakeSyntheticstests) Update(ctx context.Context, syntheticstest *v1alpha1.Syntheticstest, opts v1.UpdateOptions) (result *v1alpha1.Syntheticstest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(syntheticstestsResource, c.ns, syntheticstest), &v1alpha1.Syntheticstest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Syntheticstest), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSyntheticstests) UpdateStatus(ctx context.Context, syntheticstest *v1alpha1.Syntheticstest, opts v1.UpdateOptions) (*v1alpha1.Syntheticstest, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(syntheticstestsResource, "status", c.ns, syntheticstest), &v1alpha1.Syntheticstest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Syntheticstest), err
}

// Delete takes name of the syntheticstest and deletes it. Returns an error if one occurs.
func (c *FakeSyntheticstests) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(syntheticstestsResource, c.ns, name), &v1alpha1.Syntheticstest{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSyntheticstests) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(syntheticstestsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SyntheticstestList{})
	return err
}

// Patch applies the patch and returns the patched syntheticstest.
func (c *FakeSyntheticstests) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Syntheticstest, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(syntheticstestsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Syntheticstest{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Syntheticstest), err
}
