/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-datadog-api/apis/synthetics/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakePrivateLocations implements PrivateLocationInterface
type FakePrivateLocations struct {
	Fake *FakeSyntheticsV1alpha1
	ns   string
}

var privatelocationsResource = schema.GroupVersionResource{Group: "synthetics.datadog.kubeform.com", Version: "v1alpha1", Resource: "privatelocations"}

var privatelocationsKind = schema.GroupVersionKind{Group: "synthetics.datadog.kubeform.com", Version: "v1alpha1", Kind: "PrivateLocation"}

// Get takes name of the privateLocation, and returns the corresponding privateLocation object, and an error if there is any.
func (c *FakePrivateLocations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.PrivateLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(privatelocationsResource, c.ns, name), &v1alpha1.PrivateLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateLocation), err
}

// List takes label and field selectors, and returns the list of PrivateLocations that match those selectors.
func (c *FakePrivateLocations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.PrivateLocationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(privatelocationsResource, privatelocationsKind, c.ns, opts), &v1alpha1.PrivateLocationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.PrivateLocationList{ListMeta: obj.(*v1alpha1.PrivateLocationList).ListMeta}
	for _, item := range obj.(*v1alpha1.PrivateLocationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested privateLocations.
func (c *FakePrivateLocations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(privatelocationsResource, c.ns, opts))

}

// Create takes the representation of a privateLocation and creates it.  Returns the server's representation of the privateLocation, and an error, if there is any.
func (c *FakePrivateLocations) Create(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.CreateOptions) (result *v1alpha1.PrivateLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(privatelocationsResource, c.ns, privateLocation), &v1alpha1.PrivateLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateLocation), err
}

// Update takes the representation of a privateLocation and updates it. Returns the server's representation of the privateLocation, and an error, if there is any.
func (c *FakePrivateLocations) Update(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.UpdateOptions) (result *v1alpha1.PrivateLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(privatelocationsResource, c.ns, privateLocation), &v1alpha1.PrivateLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateLocation), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakePrivateLocations) UpdateStatus(ctx context.Context, privateLocation *v1alpha1.PrivateLocation, opts v1.UpdateOptions) (*v1alpha1.PrivateLocation, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(privatelocationsResource, "status", c.ns, privateLocation), &v1alpha1.PrivateLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateLocation), err
}

// Delete takes name of the privateLocation and deletes it. Returns an error if one occurs.
func (c *FakePrivateLocations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(privatelocationsResource, c.ns, name), &v1alpha1.PrivateLocation{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePrivateLocations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(privatelocationsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.PrivateLocationList{})
	return err
}

// Patch applies the patch and returns the patched privateLocation.
func (c *FakePrivateLocations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.PrivateLocation, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(privatelocationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.PrivateLocation{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.PrivateLocation), err
}
